/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Get_misc_weather_200_response_forecast_inner.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Get_misc_weather_200_response_forecast_inner_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Get_misc_weather_200_response_forecast_inner_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Get_misc_weather_200_response_forecast_inner
    : public ModelBase
{
public:
    Get_misc_weather_200_response_forecast_inner();
    virtual ~Get_misc_weather_200_response_forecast_inner();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Get_misc_weather_200_response_forecast_inner members


    /// <summary>
    /// 日期 YYYY-MM-DD
    /// </summary>
    utility::string_t getDate() const;
    bool dateIsSet() const;
    void unsetdate();
    void setDate(const utility::string_t& value);

    /// <summary>
    /// 星期几（&#x60;lang&#x3D;en&#x60; 时返回英文星期）
    /// </summary>
    utility::string_t getWeek() const;
    bool weekIsSet() const;
    void unsetWeek();
    void setWeek(const utility::string_t& value);

    /// <summary>
    /// 最高温度 °C
    /// </summary>
    double getTempMax() const;
    bool tempMaxIsSet() const;
    void unsetTemp_max();
    void setTempMax(double value);

    /// <summary>
    /// 最低温度 °C
    /// </summary>
    double getTempMin() const;
    bool tempMinIsSet() const;
    void unsetTemp_min();
    void setTempMin(double value);

    /// <summary>
    /// 白天天气（&#x60;lang&#x3D;en&#x60; 时返回英文）
    /// </summary>
    utility::string_t getWeatherDay() const;
    bool weatherDayIsSet() const;
    void unsetWeather_day();
    void setWeatherDay(const utility::string_t& value);

    /// <summary>
    /// 夜间天气（&#x60;lang&#x3D;en&#x60; 时返回英文）
    /// </summary>
    utility::string_t getWeatherNight() const;
    bool weatherNightIsSet() const;
    void unsetWeather_night();
    void setWeatherNight(const utility::string_t& value);

    /// <summary>
    /// 白天风向（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）
    /// </summary>
    utility::string_t getWindDirDay() const;
    bool windDirDayIsSet() const;
    void unsetWind_dir_day();
    void setWindDirDay(const utility::string_t& value);

    /// <summary>
    /// 夜间风向（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）
    /// </summary>
    utility::string_t getWindDirNight() const;
    bool windDirNightIsSet() const;
    void unsetWind_dir_night();
    void setWindDirNight(const utility::string_t& value);

    /// <summary>
    /// 白天风力（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）
    /// </summary>
    utility::string_t getWindScaleDay() const;
    bool windScaleDayIsSet() const;
    void unsetWind_scale_day();
    void setWindScaleDay(const utility::string_t& value);

    /// <summary>
    /// 夜间风力（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）
    /// </summary>
    utility::string_t getWindScaleNight() const;
    bool windScaleNightIsSet() const;
    void unsetWind_scale_night();
    void setWindScaleNight(const utility::string_t& value);

    /// <summary>
    /// 白天风速 km/h（可选）
    /// </summary>
    double getWindSpeedDay() const;
    bool windSpeedDayIsSet() const;
    void unsetWind_speed_day();
    void setWindSpeedDay(double value);

    /// <summary>
    /// 湿度 %（可选）
    /// </summary>
    double getHumidity() const;
    bool humidityIsSet() const;
    void unsetHumidity();
    void setHumidity(double value);

    /// <summary>
    /// 降水量 mm（可选）
    /// </summary>
    double getPrecip() const;
    bool precipIsSet() const;
    void unsetPrecip();
    void setPrecip(double value);

    /// <summary>
    /// 能见度 km（可选）
    /// </summary>
    double getVisibility() const;
    bool visibilityIsSet() const;
    void unsetVisibility();
    void setVisibility(double value);

    /// <summary>
    /// 紫外线指数（可选）
    /// </summary>
    double getUvIndex() const;
    bool uvIndexIsSet() const;
    void unsetUv_index();
    void setUvIndex(double value);

    /// <summary>
    /// 日出时间 HH:MM（可选）
    /// </summary>
    utility::string_t getSunrise() const;
    bool sunriseIsSet() const;
    void unsetSunrise();
    void setSunrise(const utility::string_t& value);

    /// <summary>
    /// 日落时间 HH:MM（可选）
    /// </summary>
    utility::string_t getSunset() const;
    bool sunsetIsSet() const;
    void unsetSunset();
    void setSunset(const utility::string_t& value);


protected:
    utility::string_t m_date;
    bool m_dateIsSet;

    utility::string_t m_Week;
    bool m_WeekIsSet;

    double m_Temp_max;
    bool m_Temp_maxIsSet;

    double m_Temp_min;
    bool m_Temp_minIsSet;

    utility::string_t m_Weather_day;
    bool m_Weather_dayIsSet;

    utility::string_t m_Weather_night;
    bool m_Weather_nightIsSet;

    utility::string_t m_Wind_dir_day;
    bool m_Wind_dir_dayIsSet;

    utility::string_t m_Wind_dir_night;
    bool m_Wind_dir_nightIsSet;

    utility::string_t m_Wind_scale_day;
    bool m_Wind_scale_dayIsSet;

    utility::string_t m_Wind_scale_night;
    bool m_Wind_scale_nightIsSet;

    double m_Wind_speed_day;
    bool m_Wind_speed_dayIsSet;

    double m_Humidity;
    bool m_HumidityIsSet;

    double m_Precip;
    bool m_PrecipIsSet;

    double m_Visibility;
    bool m_VisibilityIsSet;

    double m_Uv_index;
    bool m_Uv_indexIsSet;

    utility::string_t m_Sunrise;
    bool m_SunriseIsSet;

    utility::string_t m_Sunset;
    bool m_SunsetIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Get_misc_weather_200_response_forecast_inner_H_ */
