/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Get_misc_weather_200_response_air_pollutants.h
 *
 * 空气污染物分项数据（extended&#x3D;true 时返回，部分数据源可能不返回）
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Get_misc_weather_200_response_air_pollutants_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Get_misc_weather_200_response_air_pollutants_H_


#include "CppRestOpenAPIClient/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 空气污染物分项数据（extended&#x3D;true 时返回，部分数据源可能不返回）
/// </summary>
class  Get_misc_weather_200_response_air_pollutants
    : public ModelBase
{
public:
    Get_misc_weather_200_response_air_pollutants();
    virtual ~Get_misc_weather_200_response_air_pollutants();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Get_misc_weather_200_response_air_pollutants members


    /// <summary>
    /// PM2.5 μg/m³
    /// </summary>
    double getPm25() const;
    bool pm25IsSet() const;
    void unsetPm25();
    void setPm25(double value);

    /// <summary>
    /// PM10 μg/m³
    /// </summary>
    double getPm10() const;
    bool pm10IsSet() const;
    void unsetPm10();
    void setPm10(double value);

    /// <summary>
    /// 臭氧 μg/m³
    /// </summary>
    double getO3() const;
    bool o3IsSet() const;
    void unsetO3();
    void setO3(double value);

    /// <summary>
    /// 二氧化氮 μg/m³
    /// </summary>
    double getNo2() const;
    bool no2IsSet() const;
    void unsetNo2();
    void setNo2(double value);

    /// <summary>
    /// 二氧化硫 μg/m³
    /// </summary>
    double getSo2() const;
    bool so2IsSet() const;
    void unsetSo2();
    void setSo2(double value);

    /// <summary>
    /// 一氧化碳 mg/m³
    /// </summary>
    double getCo() const;
    bool coIsSet() const;
    void unsetCo();
    void setCo(double value);


protected:
    double m_Pm25;
    bool m_Pm25IsSet;

    double m_Pm10;
    bool m_Pm10IsSet;

    double m_O3;
    bool m_O3IsSet;

    double m_No2;
    bool m_No2IsSet;

    double m_So2;
    bool m_So2IsSet;

    double m_Co;
    bool m_CoIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Get_misc_weather_200_response_air_pollutants_H_ */
