/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Get_social_bilibili_replies_200_response_replies_inner_member.h
 *
 * 发表评论的用户信息。
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Get_social_bilibili_replies_200_response_replies_inner_member_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Get_social_bilibili_replies_200_response_replies_inner_member_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/Get_social_bilibili_replies_200_response_replies_inner_member_level_info.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Get_social_bilibili_replies_200_response_replies_inner_member_level_info;


/// <summary>
/// 发表评论的用户信息。
/// </summary>
class  Get_social_bilibili_replies_200_response_replies_inner_member
    : public ModelBase
{
public:
    Get_social_bilibili_replies_200_response_replies_inner_member();
    virtual ~Get_social_bilibili_replies_200_response_replies_inner_member();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Get_social_bilibili_replies_200_response_replies_inner_member members


    /// <summary>
    /// 用户昵称。
    /// </summary>
    utility::string_t getUname() const;
    bool unameIsSet() const;
    void unsetUname();
    void setUname(const utility::string_t& value);

    /// <summary>
    /// 用户性别。
    /// </summary>
    utility::string_t getSex() const;
    bool sexIsSet() const;
    void unsetSex();
    void setSex(const utility::string_t& value);

    /// <summary>
    /// 用户头像的URL。
    /// </summary>
    utility::string_t getAvatar() const;
    bool avatarIsSet() const;
    void unsetAvatar();
    void setAvatar(const utility::string_t& value);

    std::shared_ptr<Get_social_bilibili_replies_200_response_replies_inner_member_level_info> getLevelInfo() const;
    bool levelInfoIsSet() const;
    void unsetLevel_info();
    void setLevelInfo(const std::shared_ptr<Get_social_bilibili_replies_200_response_replies_inner_member_level_info>& value);


protected:
    utility::string_t m_Uname;
    bool m_UnameIsSet;

    utility::string_t m_Sex;
    bool m_SexIsSet;

    utility::string_t m_Avatar;
    bool m_AvatarIsSet;

    std::shared_ptr<Get_social_bilibili_replies_200_response_replies_inner_member_level_info> m_Level_info;
    bool m_Level_infoIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Get_social_bilibili_replies_200_response_replies_inner_member_H_ */
