/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Get_social_qq_userinfo_200_response.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Get_social_qq_userinfo_200_response_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Get_social_qq_userinfo_200_response_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Get_social_qq_userinfo_200_response
    : public ModelBase
{
public:
    Get_social_qq_userinfo_200_response();
    virtual ~Get_social_qq_userinfo_200_response();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Get_social_qq_userinfo_200_response members


    /// <summary>
    /// QQ号
    /// </summary>
    utility::string_t getQq() const;
    bool qqIsSet() const;
    void unsetQq();
    void setQq(const utility::string_t& value);

    /// <summary>
    /// 用户昵称
    /// </summary>
    utility::string_t getNickname() const;
    bool nicknameIsSet() const;
    void unsetNickname();
    void setNickname(const utility::string_t& value);

    /// <summary>
    /// 个性签名
    /// </summary>
    utility::string_t getLongNick() const;
    bool longNickIsSet() const;
    void unsetLong_nick();
    void setLongNick(const utility::string_t& value);

    /// <summary>
    /// 头像URL
    /// </summary>
    utility::string_t getAvatarUrl() const;
    bool avatarUrlIsSet() const;
    void unsetAvatar_url();
    void setAvatarUrl(const utility::string_t& value);

    /// <summary>
    /// 年龄
    /// </summary>
    int32_t getAge() const;
    bool ageIsSet() const;
    void unsetAge();
    void setAge(int32_t value);

    /// <summary>
    /// 性别
    /// </summary>
    utility::string_t getSex() const;
    bool sexIsSet() const;
    void unsetSex();
    void setSex(const utility::string_t& value);

    /// <summary>
    /// QQ个性域名
    /// </summary>
    utility::string_t getQid() const;
    bool qidIsSet() const;
    void unsetQid();
    void setQid(const utility::string_t& value);

    /// <summary>
    /// QQ等级
    /// </summary>
    int32_t getQqLevel() const;
    bool qqLevelIsSet() const;
    void unsetQq_level();
    void setQqLevel(int32_t value);

    /// <summary>
    /// 地理位置（省市）
    /// </summary>
    utility::string_t getLocation() const;
    bool locationIsSet() const;
    void unsetLocation();
    void setLocation(const utility::string_t& value);

    /// <summary>
    /// QQ邮箱
    /// </summary>
    utility::string_t getEmail() const;
    bool emailIsSet() const;
    void unsetEmail();
    void setEmail(const utility::string_t& value);

    /// <summary>
    /// 是否为VIP用户
    /// </summary>
    bool isIsVip() const;
    bool isVipIsSet() const;
    void unsetIs_vip();
    void setIsVip(bool value);

    /// <summary>
    /// VIP等级
    /// </summary>
    int32_t getVipLevel() const;
    bool vipLevelIsSet() const;
    void unsetVip_level();
    void setVipLevel(int32_t value);

    /// <summary>
    /// 注册时间（ISO 8601格式）
    /// </summary>
    utility::string_t getRegTime() const;
    bool regTimeIsSet() const;
    void unsetReg_time();
    void setRegTime(const utility::string_t& value);

    /// <summary>
    /// 最后更新时间（ISO 8601格式）
    /// </summary>
    utility::string_t getLastUpdated() const;
    bool lastUpdatedIsSet() const;
    void unsetLast_updated();
    void setLastUpdated(const utility::string_t& value);


protected:
    utility::string_t m_Qq;
    bool m_QqIsSet;

    utility::string_t m_Nickname;
    bool m_NicknameIsSet;

    utility::string_t m_Long_nick;
    bool m_Long_nickIsSet;

    utility::string_t m_Avatar_url;
    bool m_Avatar_urlIsSet;

    int32_t m_Age;
    bool m_AgeIsSet;

    utility::string_t m_Sex;
    bool m_SexIsSet;

    utility::string_t m_Qid;
    bool m_QidIsSet;

    int32_t m_Qq_level;
    bool m_Qq_levelIsSet;

    utility::string_t m_Location;
    bool m_LocationIsSet;

    utility::string_t m_Email;
    bool m_EmailIsSet;

    bool m_Is_vip;
    bool m_Is_vipIsSet;

    int32_t m_Vip_level;
    bool m_Vip_levelIsSet;

    utility::string_t m_Reg_time;
    bool m_Reg_timeIsSet;

    utility::string_t m_Last_updated;
    bool m_Last_updatedIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Get_social_qq_userinfo_200_response_H_ */
