/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Get_webparse_extractimages_200_response.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Get_webparse_extractimages_200_response_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Get_webparse_extractimages_200_response_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Get_webparse_extractimages_200_response
    : public ModelBase
{
public:
    Get_webparse_extractimages_200_response();
    virtual ~Get_webparse_extractimages_200_response();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Get_webparse_extractimages_200_response members


    /// <summary>
    /// 实际解析的网页地址。
    /// </summary>
    utility::string_t getPageUrl() const;
    bool pageUrlIsSet() const;
    void unsetPage_url();
    void setPageUrl(const utility::string_t& value);

    /// <summary>
    /// 页面中提取到的图片链接列表。
    /// </summary>
    std::vector<utility::string_t> getImageUrls() const;
    bool imageUrlsIsSet() const;
    void unsetImage_urls();
    void setImageUrls(const std::vector<utility::string_t>& value);


protected:
    utility::string_t m_Page_url;
    bool m_Page_urlIsSet;

    std::vector<utility::string_t> m_Image_urls;
    bool m_Image_urlsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Get_webparse_extractimages_200_response_H_ */
