/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Get_misc_tracking_detect_200_response_data_alternatives_inner.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Get_misc_tracking_detect_200_response_data_alternatives_inner_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Get_misc_tracking_detect_200_response_data_alternatives_inner_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Get_misc_tracking_detect_200_response_data_alternatives_inner
    : public ModelBase
{
public:
    Get_misc_tracking_detect_200_response_data_alternatives_inner();
    virtual ~Get_misc_tracking_detect_200_response_data_alternatives_inner();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Get_misc_tracking_detect_200_response_data_alternatives_inner members


    /// <summary>
    /// 快递公司编码
    /// </summary>
    utility::string_t getCode() const;
    bool codeIsSet() const;
    void unsetCode();
    void setCode(const utility::string_t& value);

    /// <summary>
    /// 快递公司名称
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);


protected:
    utility::string_t m_Code;
    bool m_CodeIsSet;

    utility::string_t m_Name;
    bool m_NameIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Get_misc_tracking_detect_200_response_data_alternatives_inner_H_ */
