/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Get_network_portscan_200_response.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Get_network_portscan_200_response_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Get_network_portscan_200_response_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Get_network_portscan_200_response
    : public ModelBase
{
public:
    Get_network_portscan_200_response();
    virtual ~Get_network_portscan_200_response();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Get_network_portscan_200_response members


    int32_t getCode() const;
    bool codeIsSet() const;
    void unsetCode();
    void setCode(int32_t value);

    utility::string_t getIp() const;
    bool ipIsSet() const;
    void unsetIp();
    void setIp(const utility::string_t& value);

    int32_t getPort() const;
    bool portIsSet() const;
    void unsetPort();
    void setPort(int32_t value);

    /// <summary>
    /// \&quot;open\&quot;, \&quot;closed\&quot;, 或 \&quot;timeout\&quot;
    /// </summary>
    utility::string_t getPortStatus() const;
    bool portStatusIsSet() const;
    void unsetPort_status();
    void setPortStatus(const utility::string_t& value);

    utility::string_t getProtocol() const;
    bool protocolIsSet() const;
    void unsetProtocol();
    void setProtocol(const utility::string_t& value);


protected:
    int32_t m_Code;
    bool m_CodeIsSet;

    utility::string_t m_Ip;
    bool m_IpIsSet;

    int32_t m_Port;
    bool m_PortIsSet;

    utility::string_t m_Port_status;
    bool m_Port_statusIsSet;

    utility::string_t m_Protocol;
    bool m_ProtocolIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Get_network_portscan_200_response_H_ */
