/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Get_github_user_200_response_organizations_inner.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Get_github_user_200_response_organizations_inner_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Get_github_user_200_response_organizations_inner_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Get_github_user_200_response_organizations_inner
    : public ModelBase
{
public:
    Get_github_user_200_response_organizations_inner();
    virtual ~Get_github_user_200_response_organizations_inner();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Get_github_user_200_response_organizations_inner members


    /// <summary>
    /// 组织登录名。
    /// </summary>
    utility::string_t getLogin() const;
    bool loginIsSet() const;
    void unsetLogin();
    void setLogin(const utility::string_t& value);

    /// <summary>
    /// 组织简介。
    /// </summary>
    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();
    void setDescription(const utility::string_t& value);

    /// <summary>
    /// 组织主页链接。
    /// </summary>
    utility::string_t getHtmlUrl() const;
    bool htmlUrlIsSet() const;
    void unsetHtml_url();
    void setHtmlUrl(const utility::string_t& value);

    /// <summary>
    /// 组织头像链接。
    /// </summary>
    utility::string_t getAvatarUrl() const;
    bool avatarUrlIsSet() const;
    void unsetAvatar_url();
    void setAvatarUrl(const utility::string_t& value);


protected:
    utility::string_t m_Login;
    bool m_LoginIsSet;

    utility::string_t m_Description;
    bool m_DescriptionIsSet;

    utility::string_t m_Html_url;
    bool m_Html_urlIsSet;

    utility::string_t m_Avatar_url;
    bool m_Avatar_urlIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Get_github_user_200_response_organizations_inner_H_ */
