/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Get_social_bilibili_replies_200_response_page.h
 *
 * 分页信息概览。
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Get_social_bilibili_replies_200_response_page_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Get_social_bilibili_replies_200_response_page_H_


#include "CppRestOpenAPIClient/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 分页信息概览。
/// </summary>
class  Get_social_bilibili_replies_200_response_page
    : public ModelBase
{
public:
    Get_social_bilibili_replies_200_response_page();
    virtual ~Get_social_bilibili_replies_200_response_page();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Get_social_bilibili_replies_200_response_page members


    /// <summary>
    /// 当前所在的页码。
    /// </summary>
    double getNum() const;
    bool numIsSet() const;
    void unsetNum();
    void setNum(double value);

    /// <summary>
    /// 每页的项数。
    /// </summary>
    double getSize() const;
    bool sizeIsSet() const;
    void unsetSize();
    void setSize(double value);

    /// <summary>
    /// 根评论（即直接评论视频的评论）的总数。
    /// </summary>
    double getCount() const;
    bool countIsSet() const;
    void unsetCount();
    void setCount(double value);

    /// <summary>
    /// 评论区总评论数，包含了所有的楼中楼回复。
    /// </summary>
    double getAcount() const;
    bool acountIsSet() const;
    void unsetAcount();
    void setAcount(double value);


protected:
    double m_Num;
    bool m_NumIsSet;

    double m_Size;
    bool m_SizeIsSet;

    double m_Count;
    bool m_CountIsSet;

    double m_Acount;
    bool m_AcountIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Get_social_bilibili_replies_200_response_page_H_ */
