/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Post_text_aes_encrypt_request.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Post_text_aes_encrypt_request_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Post_text_aes_encrypt_request_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Post_text_aes_encrypt_request
    : public ModelBase
{
public:
    Post_text_aes_encrypt_request();
    virtual ~Post_text_aes_encrypt_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Post_text_aes_encrypt_request members


    /// <summary>
    /// 密钥长度必须为 16、24 或 32 字节，分别对应 AES-128、AES-192、AES-256。
    /// </summary>
    utility::string_t getKey() const;
    bool keyIsSet() const;
    void unsetKey();
    void setKey(const utility::string_t& value);

    /// <summary>
    /// 待加密的明文文本。
    /// </summary>
    utility::string_t getText() const;
    bool textIsSet() const;
    void unsetText();
    void setText(const utility::string_t& value);


protected:
    utility::string_t m_Key;
    bool m_KeyIsSet;

    utility::string_t m_Text;
    bool m_TextIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Post_text_aes_encrypt_request_H_ */
