/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Post_text_convert_400_response.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Post_text_convert_400_response_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Post_text_convert_400_response_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Post_text_convert_400_response
    : public ModelBase
{
public:
    Post_text_convert_400_response();
    virtual ~Post_text_convert_400_response();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Post_text_convert_400_response members


    utility::string_t getErrorCode() const;
    bool errorCodeIsSet() const;
    void unsetError_code();
    void setErrorCode(const utility::string_t& value);

    utility::string_t getErrorMessage() const;
    bool errorMessageIsSet() const;
    void unsetError_message();
    void setErrorMessage(const utility::string_t& value);

    utility::string_t getErrorDetails() const;
    bool errorDetailsIsSet() const;
    void unsetError_details();
    void setErrorDetails(const utility::string_t& value);


protected:
    utility::string_t m_Error_code;
    bool m_Error_codeIsSet;

    utility::string_t m_Error_message;
    bool m_Error_messageIsSet;

    utility::string_t m_Error_details;
    bool m_Error_detailsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Post_text_convert_400_response_H_ */
