/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Post_search_aggregate_200_response.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Post_search_aggregate_200_response_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Post_search_aggregate_200_response_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/Post_search_aggregate_200_response_sources_inner.h"
#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/Post_search_aggregate_200_response_results_inner.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Post_search_aggregate_200_response_results_inner;
class Post_search_aggregate_200_response_sources_inner;


class  Post_search_aggregate_200_response
    : public ModelBase
{
public:
    Post_search_aggregate_200_response();
    virtual ~Post_search_aggregate_200_response();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Post_search_aggregate_200_response members


    /// <summary>
    /// 实际执行的搜索查询
    /// </summary>
    utility::string_t getQuery() const;
    bool queryIsSet() const;
    void unsetQuery();
    void setQuery(const utility::string_t& value);

    /// <summary>
    /// 搜索结果总数
    /// </summary>
    int32_t getTotalResults() const;
    bool totalResultsIsSet() const;
    void unsetTotal_results();
    void setTotalResults(int32_t value);

    /// <summary>
    /// 搜索结果列表
    /// </summary>
    std::vector<std::shared_ptr<Post_search_aggregate_200_response_results_inner>> getResults() const;
    bool resultsIsSet() const;
    void unsetResults();
    void setResults(const std::vector<std::shared_ptr<Post_search_aggregate_200_response_results_inner>>& value);

    /// <summary>
    /// 各搜索引擎的结果数量统计
    /// </summary>
    std::vector<std::shared_ptr<Post_search_aggregate_200_response_sources_inner>> getSources() const;
    bool sourcesIsSet() const;
    void unsetSources();
    void setSources(const std::vector<std::shared_ptr<Post_search_aggregate_200_response_sources_inner>>& value);

    /// <summary>
    /// 处理耗时（毫秒）
    /// </summary>
    int32_t getProcessTimeMs() const;
    bool processTimeMsIsSet() const;
    void unsetProcess_time_ms();
    void setProcessTimeMs(int32_t value);

    /// <summary>
    /// 结果是否来自缓存
    /// </summary>
    bool isCached() const;
    bool cachedIsSet() const;
    void unsetCached();
    void setCached(bool value);


protected:
    utility::string_t m_Query;
    bool m_QueryIsSet;

    int32_t m_Total_results;
    bool m_Total_resultsIsSet;

    std::vector<std::shared_ptr<Post_search_aggregate_200_response_results_inner>> m_Results;
    bool m_ResultsIsSet;

    std::vector<std::shared_ptr<Post_search_aggregate_200_response_sources_inner>> m_Sources;
    bool m_SourcesIsSet;

    int32_t m_Process_time_ms;
    bool m_Process_time_msIsSet;

    bool m_Cached;
    bool m_CachedIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Post_search_aggregate_200_response_H_ */
