/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Post_translate_stream_request.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Post_translate_stream_request_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Post_translate_stream_request_H_

#include <stdexcept>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  Post_translate_stream_request
    : public ModelBase
{
public:
    Post_translate_stream_request();
    virtual ~Post_translate_stream_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Post_translate_stream_request members

    enum class To_langEnum
    {
        _,
        _2,
    };
    /// <summary>
    /// 目标语言，支持：中文、英文
    /// </summary>
    enum class From_langEnum
    {
        _,
        _2,
        AUTO,
    };
    /// <summary>
    /// 源语言，支持：中文、英文、auto（自动检测）。默认为auto
    /// </summary>

    To_langEnum toTo_langEnum(const utility::string_t& value) const;
    const utility::string_t fromTo_langEnum(const To_langEnum value) const;


    From_langEnum toFrom_langEnum(const utility::string_t& value) const;
    const utility::string_t fromFrom_langEnum(const From_langEnum value) const;


    /// <summary>
    /// 待翻译的文本内容
    /// </summary>
    utility::string_t getQuery() const;
    bool queryIsSet() const;
    void unsetQuery();
    void setQuery(const utility::string_t& value);

    /// <summary>
    /// 目标语言，支持：中文、英文
    /// </summary>
    To_langEnum getToLang() const;
    bool toLangIsSet() const;
    void unsetTo_lang();
    void setToLang(const To_langEnum value);

    /// <summary>
    /// 源语言，支持：中文、英文、auto（自动检测）。默认为auto
    /// </summary>
    From_langEnum getFromLang() const;
    bool fromLangIsSet() const;
    void unsetFrom_lang();
    void setFromLang(const From_langEnum value);

    /// <summary>
    /// 语气参数，可选
    /// </summary>
    utility::string_t getTone() const;
    bool toneIsSet() const;
    void unsetTone();
    void setTone(const utility::string_t& value);


protected:
    utility::string_t m_Query;
    bool m_QueryIsSet;

    To_langEnum m_To_lang;
    bool m_To_langIsSet;

    From_langEnum m_From_lang;
    bool m_From_langIsSet;

    utility::string_t m_Tone;
    bool m_ToneIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Post_translate_stream_request_H_ */
