/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Get_social_qq_userinfo_200_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Get_social_qq_userinfo_200_response::Get_social_qq_userinfo_200_response()
{
    m_Qq = utility::conversions::to_string_t("");
    m_QqIsSet = false;
    m_Nickname = utility::conversions::to_string_t("");
    m_NicknameIsSet = false;
    m_Long_nick = utility::conversions::to_string_t("");
    m_Long_nickIsSet = false;
    m_Avatar_url = utility::conversions::to_string_t("");
    m_Avatar_urlIsSet = false;
    m_Age = 0;
    m_AgeIsSet = false;
    m_Sex = utility::conversions::to_string_t("");
    m_SexIsSet = false;
    m_Qid = utility::conversions::to_string_t("");
    m_QidIsSet = false;
    m_Qq_level = 0;
    m_Qq_levelIsSet = false;
    m_Location = utility::conversions::to_string_t("");
    m_LocationIsSet = false;
    m_Email = utility::conversions::to_string_t("");
    m_EmailIsSet = false;
    m_Is_vip = false;
    m_Is_vipIsSet = false;
    m_Vip_level = 0;
    m_Vip_levelIsSet = false;
    m_Reg_time = utility::conversions::to_string_t("");
    m_Reg_timeIsSet = false;
    m_Last_updated = utility::conversions::to_string_t("");
    m_Last_updatedIsSet = false;
}

Get_social_qq_userinfo_200_response::~Get_social_qq_userinfo_200_response()
{
}

void Get_social_qq_userinfo_200_response::validate()
{
    // TODO: implement validation
}

web::json::value Get_social_qq_userinfo_200_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_QqIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("qq"))] = ModelBase::toJson(m_Qq);
    }
    if(m_NicknameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("nickname"))] = ModelBase::toJson(m_Nickname);
    }
    if(m_Long_nickIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("long_nick"))] = ModelBase::toJson(m_Long_nick);
    }
    if(m_Avatar_urlIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("avatar_url"))] = ModelBase::toJson(m_Avatar_url);
    }
    if(m_AgeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("age"))] = ModelBase::toJson(m_Age);
    }
    if(m_SexIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("sex"))] = ModelBase::toJson(m_Sex);
    }
    if(m_QidIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("qid"))] = ModelBase::toJson(m_Qid);
    }
    if(m_Qq_levelIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("qq_level"))] = ModelBase::toJson(m_Qq_level);
    }
    if(m_LocationIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("location"))] = ModelBase::toJson(m_Location);
    }
    if(m_EmailIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("email"))] = ModelBase::toJson(m_Email);
    }
    if(m_Is_vipIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_vip"))] = ModelBase::toJson(m_Is_vip);
    }
    if(m_Vip_levelIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("vip_level"))] = ModelBase::toJson(m_Vip_level);
    }
    if(m_Reg_timeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("reg_time"))] = ModelBase::toJson(m_Reg_time);
    }
    if(m_Last_updatedIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("last_updated"))] = ModelBase::toJson(m_Last_updated);
    }

    return val;
}

bool Get_social_qq_userinfo_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("qq"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("qq")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setQq;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQq);
            setQq(refVal_setQq);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("nickname"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("nickname")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNickname;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNickname);
            setNickname(refVal_setNickname);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("long_nick"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("long_nick")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLongNick;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLongNick);
            setLongNick(refVal_setLongNick);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("avatar_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("avatar_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAvatarUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAvatarUrl);
            setAvatarUrl(refVal_setAvatarUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("age"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("age")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setAge;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAge);
            setAge(refVal_setAge);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("sex"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("sex")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSex;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSex);
            setSex(refVal_setSex);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("qid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("qid")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setQid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQid);
            setQid(refVal_setQid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("qq_level"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("qq_level")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setQqLevel;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQqLevel);
            setQqLevel(refVal_setQqLevel);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("location"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("location")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLocation;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLocation);
            setLocation(refVal_setLocation);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("email")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmail);
            setEmail(refVal_setEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_vip"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_vip")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsVip;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsVip);
            setIsVip(refVal_setIsVip);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("vip_level"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("vip_level")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setVipLevel;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVipLevel);
            setVipLevel(refVal_setVipLevel);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("reg_time"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("reg_time")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRegTime;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRegTime);
            setRegTime(refVal_setRegTime);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("last_updated"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("last_updated")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLastUpdated;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastUpdated);
            setLastUpdated(refVal_setLastUpdated);
            
        }
    }
    return ok;
}

void Get_social_qq_userinfo_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_QqIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("qq")), m_Qq));
    }
    if(m_NicknameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("nickname")), m_Nickname));
    }
    if(m_Long_nickIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("long_nick")), m_Long_nick));
    }
    if(m_Avatar_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("avatar_url")), m_Avatar_url));
    }
    if(m_AgeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("age")), m_Age));
    }
    if(m_SexIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("sex")), m_Sex));
    }
    if(m_QidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("qid")), m_Qid));
    }
    if(m_Qq_levelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("qq_level")), m_Qq_level));
    }
    if(m_LocationIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("location")), m_Location));
    }
    if(m_EmailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("email")), m_Email));
    }
    if(m_Is_vipIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_vip")), m_Is_vip));
    }
    if(m_Vip_levelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("vip_level")), m_Vip_level));
    }
    if(m_Reg_timeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("reg_time")), m_Reg_time));
    }
    if(m_Last_updatedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("last_updated")), m_Last_updated));
    }
}

bool Get_social_qq_userinfo_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("qq"))))
    {
        utility::string_t refVal_setQq;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("qq"))), refVal_setQq );
        setQq(refVal_setQq);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("nickname"))))
    {
        utility::string_t refVal_setNickname;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("nickname"))), refVal_setNickname );
        setNickname(refVal_setNickname);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("long_nick"))))
    {
        utility::string_t refVal_setLongNick;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("long_nick"))), refVal_setLongNick );
        setLongNick(refVal_setLongNick);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("avatar_url"))))
    {
        utility::string_t refVal_setAvatarUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("avatar_url"))), refVal_setAvatarUrl );
        setAvatarUrl(refVal_setAvatarUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("age"))))
    {
        int32_t refVal_setAge;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("age"))), refVal_setAge );
        setAge(refVal_setAge);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("sex"))))
    {
        utility::string_t refVal_setSex;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("sex"))), refVal_setSex );
        setSex(refVal_setSex);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("qid"))))
    {
        utility::string_t refVal_setQid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("qid"))), refVal_setQid );
        setQid(refVal_setQid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("qq_level"))))
    {
        int32_t refVal_setQqLevel;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("qq_level"))), refVal_setQqLevel );
        setQqLevel(refVal_setQqLevel);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("location"))))
    {
        utility::string_t refVal_setLocation;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("location"))), refVal_setLocation );
        setLocation(refVal_setLocation);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        utility::string_t refVal_setEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("email"))), refVal_setEmail );
        setEmail(refVal_setEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_vip"))))
    {
        bool refVal_setIsVip;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_vip"))), refVal_setIsVip );
        setIsVip(refVal_setIsVip);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("vip_level"))))
    {
        int32_t refVal_setVipLevel;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("vip_level"))), refVal_setVipLevel );
        setVipLevel(refVal_setVipLevel);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("reg_time"))))
    {
        utility::string_t refVal_setRegTime;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("reg_time"))), refVal_setRegTime );
        setRegTime(refVal_setRegTime);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("last_updated"))))
    {
        utility::string_t refVal_setLastUpdated;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("last_updated"))), refVal_setLastUpdated );
        setLastUpdated(refVal_setLastUpdated);
    }
    return ok;
}


utility::string_t Get_social_qq_userinfo_200_response::getQq() const
{
    return m_Qq;
}


void Get_social_qq_userinfo_200_response::setQq(const utility::string_t& value)
{
    m_Qq = value;
    m_QqIsSet = true;
}

bool Get_social_qq_userinfo_200_response::qqIsSet() const
{
    return m_QqIsSet;
}

void Get_social_qq_userinfo_200_response::unsetQq()
{
    m_QqIsSet = false;
}
utility::string_t Get_social_qq_userinfo_200_response::getNickname() const
{
    return m_Nickname;
}


void Get_social_qq_userinfo_200_response::setNickname(const utility::string_t& value)
{
    m_Nickname = value;
    m_NicknameIsSet = true;
}

bool Get_social_qq_userinfo_200_response::nicknameIsSet() const
{
    return m_NicknameIsSet;
}

void Get_social_qq_userinfo_200_response::unsetNickname()
{
    m_NicknameIsSet = false;
}
utility::string_t Get_social_qq_userinfo_200_response::getLongNick() const
{
    return m_Long_nick;
}


void Get_social_qq_userinfo_200_response::setLongNick(const utility::string_t& value)
{
    m_Long_nick = value;
    m_Long_nickIsSet = true;
}

bool Get_social_qq_userinfo_200_response::longNickIsSet() const
{
    return m_Long_nickIsSet;
}

void Get_social_qq_userinfo_200_response::unsetLong_nick()
{
    m_Long_nickIsSet = false;
}
utility::string_t Get_social_qq_userinfo_200_response::getAvatarUrl() const
{
    return m_Avatar_url;
}


void Get_social_qq_userinfo_200_response::setAvatarUrl(const utility::string_t& value)
{
    m_Avatar_url = value;
    m_Avatar_urlIsSet = true;
}

bool Get_social_qq_userinfo_200_response::avatarUrlIsSet() const
{
    return m_Avatar_urlIsSet;
}

void Get_social_qq_userinfo_200_response::unsetAvatar_url()
{
    m_Avatar_urlIsSet = false;
}
int32_t Get_social_qq_userinfo_200_response::getAge() const
{
    return m_Age;
}

void Get_social_qq_userinfo_200_response::setAge(int32_t value)
{
    m_Age = value;
    m_AgeIsSet = true;
}

bool Get_social_qq_userinfo_200_response::ageIsSet() const
{
    return m_AgeIsSet;
}

void Get_social_qq_userinfo_200_response::unsetAge()
{
    m_AgeIsSet = false;
}
utility::string_t Get_social_qq_userinfo_200_response::getSex() const
{
    return m_Sex;
}


void Get_social_qq_userinfo_200_response::setSex(const utility::string_t& value)
{
    m_Sex = value;
    m_SexIsSet = true;
}

bool Get_social_qq_userinfo_200_response::sexIsSet() const
{
    return m_SexIsSet;
}

void Get_social_qq_userinfo_200_response::unsetSex()
{
    m_SexIsSet = false;
}
utility::string_t Get_social_qq_userinfo_200_response::getQid() const
{
    return m_Qid;
}


void Get_social_qq_userinfo_200_response::setQid(const utility::string_t& value)
{
    m_Qid = value;
    m_QidIsSet = true;
}

bool Get_social_qq_userinfo_200_response::qidIsSet() const
{
    return m_QidIsSet;
}

void Get_social_qq_userinfo_200_response::unsetQid()
{
    m_QidIsSet = false;
}
int32_t Get_social_qq_userinfo_200_response::getQqLevel() const
{
    return m_Qq_level;
}

void Get_social_qq_userinfo_200_response::setQqLevel(int32_t value)
{
    m_Qq_level = value;
    m_Qq_levelIsSet = true;
}

bool Get_social_qq_userinfo_200_response::qqLevelIsSet() const
{
    return m_Qq_levelIsSet;
}

void Get_social_qq_userinfo_200_response::unsetQq_level()
{
    m_Qq_levelIsSet = false;
}
utility::string_t Get_social_qq_userinfo_200_response::getLocation() const
{
    return m_Location;
}


void Get_social_qq_userinfo_200_response::setLocation(const utility::string_t& value)
{
    m_Location = value;
    m_LocationIsSet = true;
}

bool Get_social_qq_userinfo_200_response::locationIsSet() const
{
    return m_LocationIsSet;
}

void Get_social_qq_userinfo_200_response::unsetLocation()
{
    m_LocationIsSet = false;
}
utility::string_t Get_social_qq_userinfo_200_response::getEmail() const
{
    return m_Email;
}


void Get_social_qq_userinfo_200_response::setEmail(const utility::string_t& value)
{
    m_Email = value;
    m_EmailIsSet = true;
}

bool Get_social_qq_userinfo_200_response::emailIsSet() const
{
    return m_EmailIsSet;
}

void Get_social_qq_userinfo_200_response::unsetEmail()
{
    m_EmailIsSet = false;
}
bool Get_social_qq_userinfo_200_response::isIsVip() const
{
    return m_Is_vip;
}

void Get_social_qq_userinfo_200_response::setIsVip(bool value)
{
    m_Is_vip = value;
    m_Is_vipIsSet = true;
}

bool Get_social_qq_userinfo_200_response::isVipIsSet() const
{
    return m_Is_vipIsSet;
}

void Get_social_qq_userinfo_200_response::unsetIs_vip()
{
    m_Is_vipIsSet = false;
}
int32_t Get_social_qq_userinfo_200_response::getVipLevel() const
{
    return m_Vip_level;
}

void Get_social_qq_userinfo_200_response::setVipLevel(int32_t value)
{
    m_Vip_level = value;
    m_Vip_levelIsSet = true;
}

bool Get_social_qq_userinfo_200_response::vipLevelIsSet() const
{
    return m_Vip_levelIsSet;
}

void Get_social_qq_userinfo_200_response::unsetVip_level()
{
    m_Vip_levelIsSet = false;
}
utility::string_t Get_social_qq_userinfo_200_response::getRegTime() const
{
    return m_Reg_time;
}


void Get_social_qq_userinfo_200_response::setRegTime(const utility::string_t& value)
{
    m_Reg_time = value;
    m_Reg_timeIsSet = true;
}

bool Get_social_qq_userinfo_200_response::regTimeIsSet() const
{
    return m_Reg_timeIsSet;
}

void Get_social_qq_userinfo_200_response::unsetReg_time()
{
    m_Reg_timeIsSet = false;
}
utility::string_t Get_social_qq_userinfo_200_response::getLastUpdated() const
{
    return m_Last_updated;
}


void Get_social_qq_userinfo_200_response::setLastUpdated(const utility::string_t& value)
{
    m_Last_updated = value;
    m_Last_updatedIsSet = true;
}

bool Get_social_qq_userinfo_200_response::lastUpdatedIsSet() const
{
    return m_Last_updatedIsSet;
}

void Get_social_qq_userinfo_200_response::unsetLast_updated()
{
    m_Last_updatedIsSet = false;
}

}
}
}
}


