/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Get_network_icp_200_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Get_network_icp_200_response::Get_network_icp_200_response()
{
    m_Code = utility::conversions::to_string_t("");
    m_CodeIsSet = false;
    m_Domain = utility::conversions::to_string_t("");
    m_DomainIsSet = false;
    m_Msg = utility::conversions::to_string_t("");
    m_MsgIsSet = false;
    m_NatureName = utility::conversions::to_string_t("");
    m_NatureNameIsSet = false;
    m_ServiceLicence = utility::conversions::to_string_t("");
    m_ServiceLicenceIsSet = false;
    m_UnitName = utility::conversions::to_string_t("");
    m_UnitNameIsSet = false;
}

Get_network_icp_200_response::~Get_network_icp_200_response()
{
}

void Get_network_icp_200_response::validate()
{
    // TODO: implement validation
}

web::json::value Get_network_icp_200_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CodeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("code"))] = ModelBase::toJson(m_Code);
    }
    if(m_DomainIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("domain"))] = ModelBase::toJson(m_Domain);
    }
    if(m_MsgIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("msg"))] = ModelBase::toJson(m_Msg);
    }
    if(m_NatureNameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("natureName"))] = ModelBase::toJson(m_NatureName);
    }
    if(m_ServiceLicenceIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("serviceLicence"))] = ModelBase::toJson(m_ServiceLicence);
    }
    if(m_UnitNameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("unitName"))] = ModelBase::toJson(m_UnitName);
    }

    return val;
}

bool Get_network_icp_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("code")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCode);
            setCode(refVal_setCode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("domain"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("domain")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDomain;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDomain);
            setDomain(refVal_setDomain);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("msg"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("msg")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMsg;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMsg);
            setMsg(refVal_setMsg);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("natureName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("natureName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNatureName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNatureName);
            setNatureName(refVal_setNatureName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("serviceLicence"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("serviceLicence")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setServiceLicence;
            ok &= ModelBase::fromJson(fieldValue, refVal_setServiceLicence);
            setServiceLicence(refVal_setServiceLicence);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("unitName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("unitName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUnitName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUnitName);
            setUnitName(refVal_setUnitName);
            
        }
    }
    return ok;
}

void Get_network_icp_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("code")), m_Code));
    }
    if(m_DomainIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("domain")), m_Domain));
    }
    if(m_MsgIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("msg")), m_Msg));
    }
    if(m_NatureNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("natureName")), m_NatureName));
    }
    if(m_ServiceLicenceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("serviceLicence")), m_ServiceLicence));
    }
    if(m_UnitNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("unitName")), m_UnitName));
    }
}

bool Get_network_icp_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        utility::string_t refVal_setCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("code"))), refVal_setCode );
        setCode(refVal_setCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("domain"))))
    {
        utility::string_t refVal_setDomain;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("domain"))), refVal_setDomain );
        setDomain(refVal_setDomain);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("msg"))))
    {
        utility::string_t refVal_setMsg;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("msg"))), refVal_setMsg );
        setMsg(refVal_setMsg);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("natureName"))))
    {
        utility::string_t refVal_setNatureName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("natureName"))), refVal_setNatureName );
        setNatureName(refVal_setNatureName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("serviceLicence"))))
    {
        utility::string_t refVal_setServiceLicence;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("serviceLicence"))), refVal_setServiceLicence );
        setServiceLicence(refVal_setServiceLicence);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("unitName"))))
    {
        utility::string_t refVal_setUnitName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("unitName"))), refVal_setUnitName );
        setUnitName(refVal_setUnitName);
    }
    return ok;
}


utility::string_t Get_network_icp_200_response::getCode() const
{
    return m_Code;
}


void Get_network_icp_200_response::setCode(const utility::string_t& value)
{
    m_Code = value;
    m_CodeIsSet = true;
}

bool Get_network_icp_200_response::codeIsSet() const
{
    return m_CodeIsSet;
}

void Get_network_icp_200_response::unsetCode()
{
    m_CodeIsSet = false;
}
utility::string_t Get_network_icp_200_response::getDomain() const
{
    return m_Domain;
}


void Get_network_icp_200_response::setDomain(const utility::string_t& value)
{
    m_Domain = value;
    m_DomainIsSet = true;
}

bool Get_network_icp_200_response::domainIsSet() const
{
    return m_DomainIsSet;
}

void Get_network_icp_200_response::unsetDomain()
{
    m_DomainIsSet = false;
}
utility::string_t Get_network_icp_200_response::getMsg() const
{
    return m_Msg;
}


void Get_network_icp_200_response::setMsg(const utility::string_t& value)
{
    m_Msg = value;
    m_MsgIsSet = true;
}

bool Get_network_icp_200_response::msgIsSet() const
{
    return m_MsgIsSet;
}

void Get_network_icp_200_response::unsetMsg()
{
    m_MsgIsSet = false;
}
utility::string_t Get_network_icp_200_response::getNatureName() const
{
    return m_NatureName;
}


void Get_network_icp_200_response::setNatureName(const utility::string_t& value)
{
    m_NatureName = value;
    m_NatureNameIsSet = true;
}

bool Get_network_icp_200_response::natureNameIsSet() const
{
    return m_NatureNameIsSet;
}

void Get_network_icp_200_response::unsetNatureName()
{
    m_NatureNameIsSet = false;
}
utility::string_t Get_network_icp_200_response::getServiceLicence() const
{
    return m_ServiceLicence;
}


void Get_network_icp_200_response::setServiceLicence(const utility::string_t& value)
{
    m_ServiceLicence = value;
    m_ServiceLicenceIsSet = true;
}

bool Get_network_icp_200_response::serviceLicenceIsSet() const
{
    return m_ServiceLicenceIsSet;
}

void Get_network_icp_200_response::unsetServiceLicence()
{
    m_ServiceLicenceIsSet = false;
}
utility::string_t Get_network_icp_200_response::getUnitName() const
{
    return m_UnitName;
}


void Get_network_icp_200_response::setUnitName(const utility::string_t& value)
{
    m_UnitName = value;
    m_UnitNameIsSet = true;
}

bool Get_network_icp_200_response::unitNameIsSet() const
{
    return m_UnitNameIsSet;
}

void Get_network_icp_200_response::unsetUnitName()
{
    m_UnitNameIsSet = false;
}

}
}
}
}


