/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Get_misc_weather_200_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Get_misc_weather_200_response::Get_misc_weather_200_response()
{
    m_Adcode = utility::conversions::to_string_t("");
    m_AdcodeIsSet = false;
    m_City = utility::conversions::to_string_t("");
    m_CityIsSet = false;
    m_Humidity = 0;
    m_HumidityIsSet = false;
    m_Province = utility::conversions::to_string_t("");
    m_ProvinceIsSet = false;
    m_Report_time = utility::conversions::to_string_t("");
    m_Report_timeIsSet = false;
    m_Temperature = 0;
    m_TemperatureIsSet = false;
    m_Weather = utility::conversions::to_string_t("");
    m_WeatherIsSet = false;
    m_Wind_direction = utility::conversions::to_string_t("");
    m_Wind_directionIsSet = false;
    m_Wind_power = utility::conversions::to_string_t("");
    m_Wind_powerIsSet = false;
}

Get_misc_weather_200_response::~Get_misc_weather_200_response()
{
}

void Get_misc_weather_200_response::validate()
{
    // TODO: implement validation
}

web::json::value Get_misc_weather_200_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AdcodeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("adcode"))] = ModelBase::toJson(m_Adcode);
    }
    if(m_CityIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("city"))] = ModelBase::toJson(m_City);
    }
    if(m_HumidityIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("humidity"))] = ModelBase::toJson(m_Humidity);
    }
    if(m_ProvinceIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("province"))] = ModelBase::toJson(m_Province);
    }
    if(m_Report_timeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("report_time"))] = ModelBase::toJson(m_Report_time);
    }
    if(m_TemperatureIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("temperature"))] = ModelBase::toJson(m_Temperature);
    }
    if(m_WeatherIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("weather"))] = ModelBase::toJson(m_Weather);
    }
    if(m_Wind_directionIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("wind_direction"))] = ModelBase::toJson(m_Wind_direction);
    }
    if(m_Wind_powerIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("wind_power"))] = ModelBase::toJson(m_Wind_power);
    }

    return val;
}

bool Get_misc_weather_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("adcode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("adcode")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAdcode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAdcode);
            setAdcode(refVal_setAdcode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("city"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("city")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCity);
            setCity(refVal_setCity);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("humidity"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("humidity")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setHumidity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHumidity);
            setHumidity(refVal_setHumidity);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("province"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("province")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProvince;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProvince);
            setProvince(refVal_setProvince);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("report_time"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("report_time")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setReportTime;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReportTime);
            setReportTime(refVal_setReportTime);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("temperature"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("temperature")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTemperature;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTemperature);
            setTemperature(refVal_setTemperature);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("weather"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("weather")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWeather;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWeather);
            setWeather(refVal_setWeather);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("wind_direction"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("wind_direction")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWindDirection;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWindDirection);
            setWindDirection(refVal_setWindDirection);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("wind_power"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("wind_power")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWindPower;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWindPower);
            setWindPower(refVal_setWindPower);
            
        }
    }
    return ok;
}

void Get_misc_weather_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AdcodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("adcode")), m_Adcode));
    }
    if(m_CityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("city")), m_City));
    }
    if(m_HumidityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("humidity")), m_Humidity));
    }
    if(m_ProvinceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("province")), m_Province));
    }
    if(m_Report_timeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("report_time")), m_Report_time));
    }
    if(m_TemperatureIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("temperature")), m_Temperature));
    }
    if(m_WeatherIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("weather")), m_Weather));
    }
    if(m_Wind_directionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("wind_direction")), m_Wind_direction));
    }
    if(m_Wind_powerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("wind_power")), m_Wind_power));
    }
}

bool Get_misc_weather_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("adcode"))))
    {
        utility::string_t refVal_setAdcode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("adcode"))), refVal_setAdcode );
        setAdcode(refVal_setAdcode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("city"))))
    {
        utility::string_t refVal_setCity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("city"))), refVal_setCity );
        setCity(refVal_setCity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("humidity"))))
    {
        int32_t refVal_setHumidity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("humidity"))), refVal_setHumidity );
        setHumidity(refVal_setHumidity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("province"))))
    {
        utility::string_t refVal_setProvince;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("province"))), refVal_setProvince );
        setProvince(refVal_setProvince);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("report_time"))))
    {
        utility::string_t refVal_setReportTime;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("report_time"))), refVal_setReportTime );
        setReportTime(refVal_setReportTime);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("temperature"))))
    {
        int32_t refVal_setTemperature;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("temperature"))), refVal_setTemperature );
        setTemperature(refVal_setTemperature);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("weather"))))
    {
        utility::string_t refVal_setWeather;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("weather"))), refVal_setWeather );
        setWeather(refVal_setWeather);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("wind_direction"))))
    {
        utility::string_t refVal_setWindDirection;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("wind_direction"))), refVal_setWindDirection );
        setWindDirection(refVal_setWindDirection);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("wind_power"))))
    {
        utility::string_t refVal_setWindPower;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("wind_power"))), refVal_setWindPower );
        setWindPower(refVal_setWindPower);
    }
    return ok;
}


utility::string_t Get_misc_weather_200_response::getAdcode() const
{
    return m_Adcode;
}


void Get_misc_weather_200_response::setAdcode(const utility::string_t& value)
{
    m_Adcode = value;
    m_AdcodeIsSet = true;
}

bool Get_misc_weather_200_response::adcodeIsSet() const
{
    return m_AdcodeIsSet;
}

void Get_misc_weather_200_response::unsetAdcode()
{
    m_AdcodeIsSet = false;
}
utility::string_t Get_misc_weather_200_response::getCity() const
{
    return m_City;
}


void Get_misc_weather_200_response::setCity(const utility::string_t& value)
{
    m_City = value;
    m_CityIsSet = true;
}

bool Get_misc_weather_200_response::cityIsSet() const
{
    return m_CityIsSet;
}

void Get_misc_weather_200_response::unsetCity()
{
    m_CityIsSet = false;
}
int32_t Get_misc_weather_200_response::getHumidity() const
{
    return m_Humidity;
}

void Get_misc_weather_200_response::setHumidity(int32_t value)
{
    m_Humidity = value;
    m_HumidityIsSet = true;
}

bool Get_misc_weather_200_response::humidityIsSet() const
{
    return m_HumidityIsSet;
}

void Get_misc_weather_200_response::unsetHumidity()
{
    m_HumidityIsSet = false;
}
utility::string_t Get_misc_weather_200_response::getProvince() const
{
    return m_Province;
}


void Get_misc_weather_200_response::setProvince(const utility::string_t& value)
{
    m_Province = value;
    m_ProvinceIsSet = true;
}

bool Get_misc_weather_200_response::provinceIsSet() const
{
    return m_ProvinceIsSet;
}

void Get_misc_weather_200_response::unsetProvince()
{
    m_ProvinceIsSet = false;
}
utility::string_t Get_misc_weather_200_response::getReportTime() const
{
    return m_Report_time;
}


void Get_misc_weather_200_response::setReportTime(const utility::string_t& value)
{
    m_Report_time = value;
    m_Report_timeIsSet = true;
}

bool Get_misc_weather_200_response::reportTimeIsSet() const
{
    return m_Report_timeIsSet;
}

void Get_misc_weather_200_response::unsetReport_time()
{
    m_Report_timeIsSet = false;
}
int32_t Get_misc_weather_200_response::getTemperature() const
{
    return m_Temperature;
}

void Get_misc_weather_200_response::setTemperature(int32_t value)
{
    m_Temperature = value;
    m_TemperatureIsSet = true;
}

bool Get_misc_weather_200_response::temperatureIsSet() const
{
    return m_TemperatureIsSet;
}

void Get_misc_weather_200_response::unsetTemperature()
{
    m_TemperatureIsSet = false;
}
utility::string_t Get_misc_weather_200_response::getWeather() const
{
    return m_Weather;
}


void Get_misc_weather_200_response::setWeather(const utility::string_t& value)
{
    m_Weather = value;
    m_WeatherIsSet = true;
}

bool Get_misc_weather_200_response::weatherIsSet() const
{
    return m_WeatherIsSet;
}

void Get_misc_weather_200_response::unsetWeather()
{
    m_WeatherIsSet = false;
}
utility::string_t Get_misc_weather_200_response::getWindDirection() const
{
    return m_Wind_direction;
}


void Get_misc_weather_200_response::setWindDirection(const utility::string_t& value)
{
    m_Wind_direction = value;
    m_Wind_directionIsSet = true;
}

bool Get_misc_weather_200_response::windDirectionIsSet() const
{
    return m_Wind_directionIsSet;
}

void Get_misc_weather_200_response::unsetWind_direction()
{
    m_Wind_directionIsSet = false;
}
utility::string_t Get_misc_weather_200_response::getWindPower() const
{
    return m_Wind_power;
}


void Get_misc_weather_200_response::setWindPower(const utility::string_t& value)
{
    m_Wind_power = value;
    m_Wind_powerIsSet = true;
}

bool Get_misc_weather_200_response::windPowerIsSet() const
{
    return m_Wind_powerIsSet;
}

void Get_misc_weather_200_response::unsetWind_power()
{
    m_Wind_powerIsSet = false;
}

}
}
}
}


