/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Get_social_bilibili_replies_200_response_replies_inner_member.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Get_social_bilibili_replies_200_response_replies_inner_member::Get_social_bilibili_replies_200_response_replies_inner_member()
{
    m_Uname = utility::conversions::to_string_t("");
    m_UnameIsSet = false;
    m_Sex = utility::conversions::to_string_t("");
    m_SexIsSet = false;
    m_Avatar = utility::conversions::to_string_t("");
    m_AvatarIsSet = false;
    m_Level_infoIsSet = false;
}

Get_social_bilibili_replies_200_response_replies_inner_member::~Get_social_bilibili_replies_200_response_replies_inner_member()
{
}

void Get_social_bilibili_replies_200_response_replies_inner_member::validate()
{
    // TODO: implement validation
}

web::json::value Get_social_bilibili_replies_200_response_replies_inner_member::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_UnameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("uname"))] = ModelBase::toJson(m_Uname);
    }
    if(m_SexIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("sex"))] = ModelBase::toJson(m_Sex);
    }
    if(m_AvatarIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("avatar"))] = ModelBase::toJson(m_Avatar);
    }
    if(m_Level_infoIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("level_info"))] = ModelBase::toJson(m_Level_info);
    }

    return val;
}

bool Get_social_bilibili_replies_200_response_replies_inner_member::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("uname"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("uname")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUname;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUname);
            setUname(refVal_setUname);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("sex"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("sex")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSex;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSex);
            setSex(refVal_setSex);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("avatar"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("avatar")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAvatar;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAvatar);
            setAvatar(refVal_setAvatar);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("level_info"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("level_info")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Get_social_bilibili_replies_200_response_replies_inner_member_level_info> refVal_setLevelInfo;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLevelInfo);
            setLevelInfo(refVal_setLevelInfo);
            
        }
    }
    return ok;
}

void Get_social_bilibili_replies_200_response_replies_inner_member::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_UnameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("uname")), m_Uname));
    }
    if(m_SexIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("sex")), m_Sex));
    }
    if(m_AvatarIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("avatar")), m_Avatar));
    }
    if(m_Level_infoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("level_info")), m_Level_info));
    }
}

bool Get_social_bilibili_replies_200_response_replies_inner_member::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("uname"))))
    {
        utility::string_t refVal_setUname;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("uname"))), refVal_setUname );
        setUname(refVal_setUname);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("sex"))))
    {
        utility::string_t refVal_setSex;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("sex"))), refVal_setSex );
        setSex(refVal_setSex);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("avatar"))))
    {
        utility::string_t refVal_setAvatar;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("avatar"))), refVal_setAvatar );
        setAvatar(refVal_setAvatar);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("level_info"))))
    {
        std::shared_ptr<Get_social_bilibili_replies_200_response_replies_inner_member_level_info> refVal_setLevelInfo;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("level_info"))), refVal_setLevelInfo );
        setLevelInfo(refVal_setLevelInfo);
    }
    return ok;
}


utility::string_t Get_social_bilibili_replies_200_response_replies_inner_member::getUname() const
{
    return m_Uname;
}


void Get_social_bilibili_replies_200_response_replies_inner_member::setUname(const utility::string_t& value)
{
    m_Uname = value;
    m_UnameIsSet = true;
}

bool Get_social_bilibili_replies_200_response_replies_inner_member::unameIsSet() const
{
    return m_UnameIsSet;
}

void Get_social_bilibili_replies_200_response_replies_inner_member::unsetUname()
{
    m_UnameIsSet = false;
}
utility::string_t Get_social_bilibili_replies_200_response_replies_inner_member::getSex() const
{
    return m_Sex;
}


void Get_social_bilibili_replies_200_response_replies_inner_member::setSex(const utility::string_t& value)
{
    m_Sex = value;
    m_SexIsSet = true;
}

bool Get_social_bilibili_replies_200_response_replies_inner_member::sexIsSet() const
{
    return m_SexIsSet;
}

void Get_social_bilibili_replies_200_response_replies_inner_member::unsetSex()
{
    m_SexIsSet = false;
}
utility::string_t Get_social_bilibili_replies_200_response_replies_inner_member::getAvatar() const
{
    return m_Avatar;
}


void Get_social_bilibili_replies_200_response_replies_inner_member::setAvatar(const utility::string_t& value)
{
    m_Avatar = value;
    m_AvatarIsSet = true;
}

bool Get_social_bilibili_replies_200_response_replies_inner_member::avatarIsSet() const
{
    return m_AvatarIsSet;
}

void Get_social_bilibili_replies_200_response_replies_inner_member::unsetAvatar()
{
    m_AvatarIsSet = false;
}
std::shared_ptr<Get_social_bilibili_replies_200_response_replies_inner_member_level_info> Get_social_bilibili_replies_200_response_replies_inner_member::getLevelInfo() const
{
    return m_Level_info;
}


void Get_social_bilibili_replies_200_response_replies_inner_member::setLevelInfo(const std::shared_ptr<Get_social_bilibili_replies_200_response_replies_inner_member_level_info>& value)
{
    m_Level_info = value;
    m_Level_infoIsSet = true;
}

bool Get_social_bilibili_replies_200_response_replies_inner_member::levelInfoIsSet() const
{
    return m_Level_infoIsSet;
}

void Get_social_bilibili_replies_200_response_replies_inner_member::unsetLevel_info()
{
    m_Level_infoIsSet = false;
}

}
}
}
}


