/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Get_search_engines_200_response_limits.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Get_search_engines_200_response_limits::Get_search_engines_200_response_limits()
{
    m_r_default = 0;
    m_r_defaultIsSet = false;
    m_Max = 0;
    m_MaxIsSet = false;
}

Get_search_engines_200_response_limits::~Get_search_engines_200_response_limits()
{
}

void Get_search_engines_200_response_limits::validate()
{
    // TODO: implement validation
}

web::json::value Get_search_engines_200_response_limits::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_r_defaultIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("default"))] = ModelBase::toJson(m_r_default);
    }
    if(m_MaxIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("max"))] = ModelBase::toJson(m_Max);
    }

    return val;
}

bool Get_search_engines_200_response_limits::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("default"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("default")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setRDefault;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRDefault);
            setRDefault(refVal_setRDefault);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("max"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("max")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setMax;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMax);
            setMax(refVal_setMax);
            
        }
    }
    return ok;
}

void Get_search_engines_200_response_limits::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_r_defaultIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("default")), m_r_default));
    }
    if(m_MaxIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("max")), m_Max));
    }
}

bool Get_search_engines_200_response_limits::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("default"))))
    {
        int32_t refVal_setRDefault;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("default"))), refVal_setRDefault );
        setRDefault(refVal_setRDefault);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("max"))))
    {
        int32_t refVal_setMax;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("max"))), refVal_setMax );
        setMax(refVal_setMax);
    }
    return ok;
}


int32_t Get_search_engines_200_response_limits::getRDefault() const
{
    return m_r_default;
}

void Get_search_engines_200_response_limits::setRDefault(int32_t value)
{
    m_r_default = value;
    m_r_defaultIsSet = true;
}

bool Get_search_engines_200_response_limits::rDefaultIsSet() const
{
    return m_r_defaultIsSet;
}

void Get_search_engines_200_response_limits::unsetr_default()
{
    m_r_defaultIsSet = false;
}
int32_t Get_search_engines_200_response_limits::getMax() const
{
    return m_Max;
}

void Get_search_engines_200_response_limits::setMax(int32_t value)
{
    m_Max = value;
    m_MaxIsSet = true;
}

bool Get_search_engines_200_response_limits::maxIsSet() const
{
    return m_MaxIsSet;
}

void Get_search_engines_200_response_limits::unsetMax()
{
    m_MaxIsSet = false;
}

}
}
}
}


