/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Get_github_user_200_response_organizations_inner.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Get_github_user_200_response_organizations_inner::Get_github_user_200_response_organizations_inner()
{
    m_Login = utility::conversions::to_string_t("");
    m_LoginIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_Html_url = utility::conversions::to_string_t("");
    m_Html_urlIsSet = false;
    m_Avatar_url = utility::conversions::to_string_t("");
    m_Avatar_urlIsSet = false;
}

Get_github_user_200_response_organizations_inner::~Get_github_user_200_response_organizations_inner()
{
}

void Get_github_user_200_response_organizations_inner::validate()
{
    // TODO: implement validation
}

web::json::value Get_github_user_200_response_organizations_inner::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_LoginIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("login"))] = ModelBase::toJson(m_Login);
    }
    if(m_DescriptionIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_Html_urlIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("html_url"))] = ModelBase::toJson(m_Html_url);
    }
    if(m_Avatar_urlIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("avatar_url"))] = ModelBase::toJson(m_Avatar_url);
    }

    return val;
}

bool Get_github_user_200_response_organizations_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("login"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("login")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLogin;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLogin);
            setLogin(refVal_setLogin);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("html_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("html_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setHtmlUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHtmlUrl);
            setHtmlUrl(refVal_setHtmlUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("avatar_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("avatar_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAvatarUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAvatarUrl);
            setAvatarUrl(refVal_setAvatarUrl);
            
        }
    }
    return ok;
}

void Get_github_user_200_response_organizations_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_LoginIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("login")), m_Login));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description));
    }
    if(m_Html_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("html_url")), m_Html_url));
    }
    if(m_Avatar_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("avatar_url")), m_Avatar_url));
    }
}

bool Get_github_user_200_response_organizations_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("login"))))
    {
        utility::string_t refVal_setLogin;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("login"))), refVal_setLogin );
        setLogin(refVal_setLogin);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("html_url"))))
    {
        utility::string_t refVal_setHtmlUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("html_url"))), refVal_setHtmlUrl );
        setHtmlUrl(refVal_setHtmlUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("avatar_url"))))
    {
        utility::string_t refVal_setAvatarUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("avatar_url"))), refVal_setAvatarUrl );
        setAvatarUrl(refVal_setAvatarUrl);
    }
    return ok;
}


utility::string_t Get_github_user_200_response_organizations_inner::getLogin() const
{
    return m_Login;
}


void Get_github_user_200_response_organizations_inner::setLogin(const utility::string_t& value)
{
    m_Login = value;
    m_LoginIsSet = true;
}

bool Get_github_user_200_response_organizations_inner::loginIsSet() const
{
    return m_LoginIsSet;
}

void Get_github_user_200_response_organizations_inner::unsetLogin()
{
    m_LoginIsSet = false;
}
utility::string_t Get_github_user_200_response_organizations_inner::getDescription() const
{
    return m_Description;
}


void Get_github_user_200_response_organizations_inner::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool Get_github_user_200_response_organizations_inner::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void Get_github_user_200_response_organizations_inner::unsetDescription()
{
    m_DescriptionIsSet = false;
}
utility::string_t Get_github_user_200_response_organizations_inner::getHtmlUrl() const
{
    return m_Html_url;
}


void Get_github_user_200_response_organizations_inner::setHtmlUrl(const utility::string_t& value)
{
    m_Html_url = value;
    m_Html_urlIsSet = true;
}

bool Get_github_user_200_response_organizations_inner::htmlUrlIsSet() const
{
    return m_Html_urlIsSet;
}

void Get_github_user_200_response_organizations_inner::unsetHtml_url()
{
    m_Html_urlIsSet = false;
}
utility::string_t Get_github_user_200_response_organizations_inner::getAvatarUrl() const
{
    return m_Avatar_url;
}


void Get_github_user_200_response_organizations_inner::setAvatarUrl(const utility::string_t& value)
{
    m_Avatar_url = value;
    m_Avatar_urlIsSet = true;
}

bool Get_github_user_200_response_organizations_inner::avatarUrlIsSet() const
{
    return m_Avatar_urlIsSet;
}

void Get_github_user_200_response_organizations_inner::unsetAvatar_url()
{
    m_Avatar_urlIsSet = false;
}

}
}
}
}


