/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Get_network_portscan_200_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Get_network_portscan_200_response::Get_network_portscan_200_response()
{
    m_Code = 0;
    m_CodeIsSet = false;
    m_Ip = utility::conversions::to_string_t("");
    m_IpIsSet = false;
    m_Port = 0;
    m_PortIsSet = false;
    m_Port_status = utility::conversions::to_string_t("");
    m_Port_statusIsSet = false;
    m_Protocol = utility::conversions::to_string_t("");
    m_ProtocolIsSet = false;
}

Get_network_portscan_200_response::~Get_network_portscan_200_response()
{
}

void Get_network_portscan_200_response::validate()
{
    // TODO: implement validation
}

web::json::value Get_network_portscan_200_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CodeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("code"))] = ModelBase::toJson(m_Code);
    }
    if(m_IpIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("ip"))] = ModelBase::toJson(m_Ip);
    }
    if(m_PortIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("port"))] = ModelBase::toJson(m_Port);
    }
    if(m_Port_statusIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("port_status"))] = ModelBase::toJson(m_Port_status);
    }
    if(m_ProtocolIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("protocol"))] = ModelBase::toJson(m_Protocol);
    }

    return val;
}

bool Get_network_portscan_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("code")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCode);
            setCode(refVal_setCode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("ip"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("ip")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setIp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIp);
            setIp(refVal_setIp);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("port"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("port")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPort;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPort);
            setPort(refVal_setPort);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("port_status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("port_status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPortStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPortStatus);
            setPortStatus(refVal_setPortStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("protocol"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("protocol")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProtocol;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProtocol);
            setProtocol(refVal_setProtocol);
            
        }
    }
    return ok;
}

void Get_network_portscan_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("code")), m_Code));
    }
    if(m_IpIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("ip")), m_Ip));
    }
    if(m_PortIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("port")), m_Port));
    }
    if(m_Port_statusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("port_status")), m_Port_status));
    }
    if(m_ProtocolIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("protocol")), m_Protocol));
    }
}

bool Get_network_portscan_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        int32_t refVal_setCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("code"))), refVal_setCode );
        setCode(refVal_setCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("ip"))))
    {
        utility::string_t refVal_setIp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("ip"))), refVal_setIp );
        setIp(refVal_setIp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("port"))))
    {
        int32_t refVal_setPort;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("port"))), refVal_setPort );
        setPort(refVal_setPort);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("port_status"))))
    {
        utility::string_t refVal_setPortStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("port_status"))), refVal_setPortStatus );
        setPortStatus(refVal_setPortStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("protocol"))))
    {
        utility::string_t refVal_setProtocol;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("protocol"))), refVal_setProtocol );
        setProtocol(refVal_setProtocol);
    }
    return ok;
}


int32_t Get_network_portscan_200_response::getCode() const
{
    return m_Code;
}

void Get_network_portscan_200_response::setCode(int32_t value)
{
    m_Code = value;
    m_CodeIsSet = true;
}

bool Get_network_portscan_200_response::codeIsSet() const
{
    return m_CodeIsSet;
}

void Get_network_portscan_200_response::unsetCode()
{
    m_CodeIsSet = false;
}
utility::string_t Get_network_portscan_200_response::getIp() const
{
    return m_Ip;
}


void Get_network_portscan_200_response::setIp(const utility::string_t& value)
{
    m_Ip = value;
    m_IpIsSet = true;
}

bool Get_network_portscan_200_response::ipIsSet() const
{
    return m_IpIsSet;
}

void Get_network_portscan_200_response::unsetIp()
{
    m_IpIsSet = false;
}
int32_t Get_network_portscan_200_response::getPort() const
{
    return m_Port;
}

void Get_network_portscan_200_response::setPort(int32_t value)
{
    m_Port = value;
    m_PortIsSet = true;
}

bool Get_network_portscan_200_response::portIsSet() const
{
    return m_PortIsSet;
}

void Get_network_portscan_200_response::unsetPort()
{
    m_PortIsSet = false;
}
utility::string_t Get_network_portscan_200_response::getPortStatus() const
{
    return m_Port_status;
}


void Get_network_portscan_200_response::setPortStatus(const utility::string_t& value)
{
    m_Port_status = value;
    m_Port_statusIsSet = true;
}

bool Get_network_portscan_200_response::portStatusIsSet() const
{
    return m_Port_statusIsSet;
}

void Get_network_portscan_200_response::unsetPort_status()
{
    m_Port_statusIsSet = false;
}
utility::string_t Get_network_portscan_200_response::getProtocol() const
{
    return m_Protocol;
}


void Get_network_portscan_200_response::setProtocol(const utility::string_t& value)
{
    m_Protocol = value;
    m_ProtocolIsSet = true;
}

bool Get_network_portscan_200_response::protocolIsSet() const
{
    return m_ProtocolIsSet;
}

void Get_network_portscan_200_response::unsetProtocol()
{
    m_ProtocolIsSet = false;
}

}
}
}
}


