/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Get_misc_tracking_carriers_200_response_data.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Get_misc_tracking_carriers_200_response_data::Get_misc_tracking_carriers_200_response_data()
{
    m_Total = 0;
    m_TotalIsSet = false;
    m_CarriersIsSet = false;
}

Get_misc_tracking_carriers_200_response_data::~Get_misc_tracking_carriers_200_response_data()
{
}

void Get_misc_tracking_carriers_200_response_data::validate()
{
    // TODO: implement validation
}

web::json::value Get_misc_tracking_carriers_200_response_data::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_TotalIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("total"))] = ModelBase::toJson(m_Total);
    }
    if(m_CarriersIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("carriers"))] = ModelBase::toJson(m_Carriers);
    }

    return val;
}

bool Get_misc_tracking_carriers_200_response_data::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("total"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("total")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotal;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotal);
            setTotal(refVal_setTotal);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("carriers"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("carriers")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Get_misc_tracking_carriers_200_response_data_carriers_inner>> refVal_setCarriers;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCarriers);
            setCarriers(refVal_setCarriers);
            
        }
    }
    return ok;
}

void Get_misc_tracking_carriers_200_response_data::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_TotalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("total")), m_Total));
    }
    if(m_CarriersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("carriers")), m_Carriers));
    }
}

bool Get_misc_tracking_carriers_200_response_data::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("total"))))
    {
        int32_t refVal_setTotal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("total"))), refVal_setTotal );
        setTotal(refVal_setTotal);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("carriers"))))
    {
        std::vector<std::shared_ptr<Get_misc_tracking_carriers_200_response_data_carriers_inner>> refVal_setCarriers;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("carriers"))), refVal_setCarriers );
        setCarriers(refVal_setCarriers);
    }
    return ok;
}


int32_t Get_misc_tracking_carriers_200_response_data::getTotal() const
{
    return m_Total;
}

void Get_misc_tracking_carriers_200_response_data::setTotal(int32_t value)
{
    m_Total = value;
    m_TotalIsSet = true;
}

bool Get_misc_tracking_carriers_200_response_data::totalIsSet() const
{
    return m_TotalIsSet;
}

void Get_misc_tracking_carriers_200_response_data::unsetTotal()
{
    m_TotalIsSet = false;
}
std::vector<std::shared_ptr<Get_misc_tracking_carriers_200_response_data_carriers_inner>> Get_misc_tracking_carriers_200_response_data::getCarriers() const
{
    return m_Carriers;
}


void Get_misc_tracking_carriers_200_response_data::setCarriers(const std::vector<std::shared_ptr<Get_misc_tracking_carriers_200_response_data_carriers_inner>>& value)
{
    m_Carriers = value;
    m_CarriersIsSet = true;
}

bool Get_misc_tracking_carriers_200_response_data::carriersIsSet() const
{
    return m_CarriersIsSet;
}

void Get_misc_tracking_carriers_200_response_data::unsetCarriers()
{
    m_CarriersIsSet = false;
}

}
}
}
}


