/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Get_social_bilibili_liveroom_200_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Get_social_bilibili_liveroom_200_response::Get_social_bilibili_liveroom_200_response()
{
    m_Uid = 0.0;
    m_UidIsSet = false;
    m_Room_id = 0.0;
    m_Room_idIsSet = false;
    m_Short_id = 0.0;
    m_Short_idIsSet = false;
    m_Attention = 0.0;
    m_AttentionIsSet = false;
    m_Online = 0.0;
    m_OnlineIsSet = false;
    m_Live_status = 0.0;
    m_Live_statusIsSet = false;
    m_Area_id = 0.0;
    m_Area_idIsSet = false;
    m_Parent_area_name = utility::conversions::to_string_t("");
    m_Parent_area_nameIsSet = false;
    m_Area_name = utility::conversions::to_string_t("");
    m_Area_nameIsSet = false;
    m_Background = utility::conversions::to_string_t("");
    m_BackgroundIsSet = false;
    m_Title = utility::conversions::to_string_t("");
    m_TitleIsSet = false;
    m_User_cover = utility::conversions::to_string_t("");
    m_User_coverIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_Live_time = utility::conversions::to_string_t("");
    m_Live_timeIsSet = false;
    m_Tags = utility::conversions::to_string_t("");
    m_TagsIsSet = false;
    m_Hot_wordsIsSet = false;
    m_New_pendantsIsSet = false;
}

Get_social_bilibili_liveroom_200_response::~Get_social_bilibili_liveroom_200_response()
{
}

void Get_social_bilibili_liveroom_200_response::validate()
{
    // TODO: implement validation
}

web::json::value Get_social_bilibili_liveroom_200_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_UidIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("uid"))] = ModelBase::toJson(m_Uid);
    }
    if(m_Room_idIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("room_id"))] = ModelBase::toJson(m_Room_id);
    }
    if(m_Short_idIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("short_id"))] = ModelBase::toJson(m_Short_id);
    }
    if(m_AttentionIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("attention"))] = ModelBase::toJson(m_Attention);
    }
    if(m_OnlineIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("online"))] = ModelBase::toJson(m_Online);
    }
    if(m_Live_statusIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("live_status"))] = ModelBase::toJson(m_Live_status);
    }
    if(m_Area_idIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("area_id"))] = ModelBase::toJson(m_Area_id);
    }
    if(m_Parent_area_nameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("parent_area_name"))] = ModelBase::toJson(m_Parent_area_name);
    }
    if(m_Area_nameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("area_name"))] = ModelBase::toJson(m_Area_name);
    }
    if(m_BackgroundIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("background"))] = ModelBase::toJson(m_Background);
    }
    if(m_TitleIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("title"))] = ModelBase::toJson(m_Title);
    }
    if(m_User_coverIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("user_cover"))] = ModelBase::toJson(m_User_cover);
    }
    if(m_DescriptionIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_Live_timeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("live_time"))] = ModelBase::toJson(m_Live_time);
    }
    if(m_TagsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("tags"))] = ModelBase::toJson(m_Tags);
    }
    if(m_Hot_wordsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("hot_words"))] = ModelBase::toJson(m_Hot_words);
    }
    if(m_New_pendantsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("new_pendants"))] = ModelBase::toJson(m_New_pendants);
    }

    return val;
}

bool Get_social_bilibili_liveroom_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("uid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("uid")));
        if(!fieldValue.is_null())
        {
            double refVal_setUid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUid);
            setUid(refVal_setUid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("room_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("room_id")));
        if(!fieldValue.is_null())
        {
            double refVal_setRoomId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRoomId);
            setRoomId(refVal_setRoomId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("short_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("short_id")));
        if(!fieldValue.is_null())
        {
            double refVal_setShortId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShortId);
            setShortId(refVal_setShortId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("attention"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("attention")));
        if(!fieldValue.is_null())
        {
            double refVal_setAttention;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAttention);
            setAttention(refVal_setAttention);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("online"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("online")));
        if(!fieldValue.is_null())
        {
            double refVal_setOnline;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOnline);
            setOnline(refVal_setOnline);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("live_status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("live_status")));
        if(!fieldValue.is_null())
        {
            double refVal_setLiveStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLiveStatus);
            setLiveStatus(refVal_setLiveStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("area_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("area_id")));
        if(!fieldValue.is_null())
        {
            double refVal_setAreaId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAreaId);
            setAreaId(refVal_setAreaId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("parent_area_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("parent_area_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setParentAreaName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setParentAreaName);
            setParentAreaName(refVal_setParentAreaName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("area_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("area_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAreaName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAreaName);
            setAreaName(refVal_setAreaName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("background"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("background")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBackground;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBackground);
            setBackground(refVal_setBackground);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitle);
            setTitle(refVal_setTitle);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("user_cover"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("user_cover")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUserCover;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUserCover);
            setUserCover(refVal_setUserCover);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("live_time"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("live_time")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLiveTime;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLiveTime);
            setLiveTime(refVal_setLiveTime);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tags"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tags")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTags;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTags);
            setTags(refVal_setTags);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("hot_words"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("hot_words")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setHotWords;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHotWords);
            setHotWords(refVal_setHotWords);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("new_pendants"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("new_pendants")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Object> refVal_setNewPendants;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNewPendants);
            setNewPendants(refVal_setNewPendants);
            
        }
    }
    return ok;
}

void Get_social_bilibili_liveroom_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_UidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("uid")), m_Uid));
    }
    if(m_Room_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("room_id")), m_Room_id));
    }
    if(m_Short_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("short_id")), m_Short_id));
    }
    if(m_AttentionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("attention")), m_Attention));
    }
    if(m_OnlineIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("online")), m_Online));
    }
    if(m_Live_statusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("live_status")), m_Live_status));
    }
    if(m_Area_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("area_id")), m_Area_id));
    }
    if(m_Parent_area_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("parent_area_name")), m_Parent_area_name));
    }
    if(m_Area_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("area_name")), m_Area_name));
    }
    if(m_BackgroundIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("background")), m_Background));
    }
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("title")), m_Title));
    }
    if(m_User_coverIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("user_cover")), m_User_cover));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description));
    }
    if(m_Live_timeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("live_time")), m_Live_time));
    }
    if(m_TagsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tags")), m_Tags));
    }
    if(m_Hot_wordsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("hot_words")), m_Hot_words));
    }
    if(m_New_pendantsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("new_pendants")), m_New_pendants));
    }
}

bool Get_social_bilibili_liveroom_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("uid"))))
    {
        double refVal_setUid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("uid"))), refVal_setUid );
        setUid(refVal_setUid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("room_id"))))
    {
        double refVal_setRoomId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("room_id"))), refVal_setRoomId );
        setRoomId(refVal_setRoomId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("short_id"))))
    {
        double refVal_setShortId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("short_id"))), refVal_setShortId );
        setShortId(refVal_setShortId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("attention"))))
    {
        double refVal_setAttention;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("attention"))), refVal_setAttention );
        setAttention(refVal_setAttention);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("online"))))
    {
        double refVal_setOnline;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("online"))), refVal_setOnline );
        setOnline(refVal_setOnline);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("live_status"))))
    {
        double refVal_setLiveStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("live_status"))), refVal_setLiveStatus );
        setLiveStatus(refVal_setLiveStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("area_id"))))
    {
        double refVal_setAreaId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("area_id"))), refVal_setAreaId );
        setAreaId(refVal_setAreaId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("parent_area_name"))))
    {
        utility::string_t refVal_setParentAreaName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("parent_area_name"))), refVal_setParentAreaName );
        setParentAreaName(refVal_setParentAreaName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("area_name"))))
    {
        utility::string_t refVal_setAreaName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("area_name"))), refVal_setAreaName );
        setAreaName(refVal_setAreaName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("background"))))
    {
        utility::string_t refVal_setBackground;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("background"))), refVal_setBackground );
        setBackground(refVal_setBackground);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        utility::string_t refVal_setTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("title"))), refVal_setTitle );
        setTitle(refVal_setTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("user_cover"))))
    {
        utility::string_t refVal_setUserCover;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("user_cover"))), refVal_setUserCover );
        setUserCover(refVal_setUserCover);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("live_time"))))
    {
        utility::string_t refVal_setLiveTime;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("live_time"))), refVal_setLiveTime );
        setLiveTime(refVal_setLiveTime);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tags"))))
    {
        utility::string_t refVal_setTags;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tags"))), refVal_setTags );
        setTags(refVal_setTags);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("hot_words"))))
    {
        std::vector<utility::string_t> refVal_setHotWords;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("hot_words"))), refVal_setHotWords );
        setHotWords(refVal_setHotWords);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("new_pendants"))))
    {
        std::shared_ptr<Object> refVal_setNewPendants;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("new_pendants"))), refVal_setNewPendants );
        setNewPendants(refVal_setNewPendants);
    }
    return ok;
}


double Get_social_bilibili_liveroom_200_response::getUid() const
{
    return m_Uid;
}

void Get_social_bilibili_liveroom_200_response::setUid(double value)
{
    m_Uid = value;
    m_UidIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::uidIsSet() const
{
    return m_UidIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetUid()
{
    m_UidIsSet = false;
}
double Get_social_bilibili_liveroom_200_response::getRoomId() const
{
    return m_Room_id;
}

void Get_social_bilibili_liveroom_200_response::setRoomId(double value)
{
    m_Room_id = value;
    m_Room_idIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::roomIdIsSet() const
{
    return m_Room_idIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetRoom_id()
{
    m_Room_idIsSet = false;
}
double Get_social_bilibili_liveroom_200_response::getShortId() const
{
    return m_Short_id;
}

void Get_social_bilibili_liveroom_200_response::setShortId(double value)
{
    m_Short_id = value;
    m_Short_idIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::shortIdIsSet() const
{
    return m_Short_idIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetShort_id()
{
    m_Short_idIsSet = false;
}
double Get_social_bilibili_liveroom_200_response::getAttention() const
{
    return m_Attention;
}

void Get_social_bilibili_liveroom_200_response::setAttention(double value)
{
    m_Attention = value;
    m_AttentionIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::attentionIsSet() const
{
    return m_AttentionIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetAttention()
{
    m_AttentionIsSet = false;
}
double Get_social_bilibili_liveroom_200_response::getOnline() const
{
    return m_Online;
}

void Get_social_bilibili_liveroom_200_response::setOnline(double value)
{
    m_Online = value;
    m_OnlineIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::onlineIsSet() const
{
    return m_OnlineIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetOnline()
{
    m_OnlineIsSet = false;
}
double Get_social_bilibili_liveroom_200_response::getLiveStatus() const
{
    return m_Live_status;
}

void Get_social_bilibili_liveroom_200_response::setLiveStatus(double value)
{
    m_Live_status = value;
    m_Live_statusIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::liveStatusIsSet() const
{
    return m_Live_statusIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetLive_status()
{
    m_Live_statusIsSet = false;
}
double Get_social_bilibili_liveroom_200_response::getAreaId() const
{
    return m_Area_id;
}

void Get_social_bilibili_liveroom_200_response::setAreaId(double value)
{
    m_Area_id = value;
    m_Area_idIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::areaIdIsSet() const
{
    return m_Area_idIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetArea_id()
{
    m_Area_idIsSet = false;
}
utility::string_t Get_social_bilibili_liveroom_200_response::getParentAreaName() const
{
    return m_Parent_area_name;
}


void Get_social_bilibili_liveroom_200_response::setParentAreaName(const utility::string_t& value)
{
    m_Parent_area_name = value;
    m_Parent_area_nameIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::parentAreaNameIsSet() const
{
    return m_Parent_area_nameIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetParent_area_name()
{
    m_Parent_area_nameIsSet = false;
}
utility::string_t Get_social_bilibili_liveroom_200_response::getAreaName() const
{
    return m_Area_name;
}


void Get_social_bilibili_liveroom_200_response::setAreaName(const utility::string_t& value)
{
    m_Area_name = value;
    m_Area_nameIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::areaNameIsSet() const
{
    return m_Area_nameIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetArea_name()
{
    m_Area_nameIsSet = false;
}
utility::string_t Get_social_bilibili_liveroom_200_response::getBackground() const
{
    return m_Background;
}


void Get_social_bilibili_liveroom_200_response::setBackground(const utility::string_t& value)
{
    m_Background = value;
    m_BackgroundIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::backgroundIsSet() const
{
    return m_BackgroundIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetBackground()
{
    m_BackgroundIsSet = false;
}
utility::string_t Get_social_bilibili_liveroom_200_response::getTitle() const
{
    return m_Title;
}


void Get_social_bilibili_liveroom_200_response::setTitle(const utility::string_t& value)
{
    m_Title = value;
    m_TitleIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::titleIsSet() const
{
    return m_TitleIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetTitle()
{
    m_TitleIsSet = false;
}
utility::string_t Get_social_bilibili_liveroom_200_response::getUserCover() const
{
    return m_User_cover;
}


void Get_social_bilibili_liveroom_200_response::setUserCover(const utility::string_t& value)
{
    m_User_cover = value;
    m_User_coverIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::userCoverIsSet() const
{
    return m_User_coverIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetUser_cover()
{
    m_User_coverIsSet = false;
}
utility::string_t Get_social_bilibili_liveroom_200_response::getDescription() const
{
    return m_Description;
}


void Get_social_bilibili_liveroom_200_response::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetDescription()
{
    m_DescriptionIsSet = false;
}
utility::string_t Get_social_bilibili_liveroom_200_response::getLiveTime() const
{
    return m_Live_time;
}


void Get_social_bilibili_liveroom_200_response::setLiveTime(const utility::string_t& value)
{
    m_Live_time = value;
    m_Live_timeIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::liveTimeIsSet() const
{
    return m_Live_timeIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetLive_time()
{
    m_Live_timeIsSet = false;
}
utility::string_t Get_social_bilibili_liveroom_200_response::getTags() const
{
    return m_Tags;
}


void Get_social_bilibili_liveroom_200_response::setTags(const utility::string_t& value)
{
    m_Tags = value;
    m_TagsIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::tagsIsSet() const
{
    return m_TagsIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetTags()
{
    m_TagsIsSet = false;
}
std::vector<utility::string_t> Get_social_bilibili_liveroom_200_response::getHotWords() const
{
    return m_Hot_words;
}


void Get_social_bilibili_liveroom_200_response::setHotWords(const std::vector<utility::string_t>& value)
{
    m_Hot_words = value;
    m_Hot_wordsIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::hotWordsIsSet() const
{
    return m_Hot_wordsIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetHot_words()
{
    m_Hot_wordsIsSet = false;
}
std::shared_ptr<Object> Get_social_bilibili_liveroom_200_response::getNewPendants() const
{
    return m_New_pendants;
}


void Get_social_bilibili_liveroom_200_response::setNewPendants(const std::shared_ptr<Object>& value)
{
    m_New_pendants = value;
    m_New_pendantsIsSet = true;
}

bool Get_social_bilibili_liveroom_200_response::newPendantsIsSet() const
{
    return m_New_pendantsIsSet;
}

void Get_social_bilibili_liveroom_200_response::unsetNew_pendants()
{
    m_New_pendantsIsSet = false;
}

}
}
}
}


