/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner()
{
    m_Aid = 0.0;
    m_AidIsSet = false;
    m_Type = 0.0;
    m_TypeIsSet = false;
    m_Desc = utility::conversions::to_string_t("");
    m_DescIsSet = false;
    m_Weekly_recommend_num = 0.0;
    m_Weekly_recommend_numIsSet = false;
}

Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::~Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner()
{
}

void Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::validate()
{
    // TODO: implement validation
}

web::json::value Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AidIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("aid"))] = ModelBase::toJson(m_Aid);
    }
    if(m_TypeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("type"))] = ModelBase::toJson(m_Type);
    }
    if(m_DescIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("desc"))] = ModelBase::toJson(m_Desc);
    }
    if(m_Weekly_recommend_numIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("weekly_recommend_num"))] = ModelBase::toJson(m_Weekly_recommend_num);
    }

    return val;
}

bool Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("aid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("aid")));
        if(!fieldValue.is_null())
        {
            double refVal_setAid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAid);
            setAid(refVal_setAid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("type")));
        if(!fieldValue.is_null())
        {
            double refVal_setType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setType);
            setType(refVal_setType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("desc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("desc")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDesc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDesc);
            setDesc(refVal_setDesc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("weekly_recommend_num"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("weekly_recommend_num")));
        if(!fieldValue.is_null())
        {
            double refVal_setWeeklyRecommendNum;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWeeklyRecommendNum);
            setWeeklyRecommendNum(refVal_setWeeklyRecommendNum);
            
        }
    }
    return ok;
}

void Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("aid")), m_Aid));
    }
    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("type")), m_Type));
    }
    if(m_DescIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("desc")), m_Desc));
    }
    if(m_Weekly_recommend_numIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("weekly_recommend_num")), m_Weekly_recommend_num));
    }
}

bool Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("aid"))))
    {
        double refVal_setAid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("aid"))), refVal_setAid );
        setAid(refVal_setAid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        double refVal_setType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("type"))), refVal_setType );
        setType(refVal_setType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("desc"))))
    {
        utility::string_t refVal_setDesc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("desc"))), refVal_setDesc );
        setDesc(refVal_setDesc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("weekly_recommend_num"))))
    {
        double refVal_setWeeklyRecommendNum;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("weekly_recommend_num"))), refVal_setWeeklyRecommendNum );
        setWeeklyRecommendNum(refVal_setWeeklyRecommendNum);
    }
    return ok;
}


double Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::getAid() const
{
    return m_Aid;
}

void Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::setAid(double value)
{
    m_Aid = value;
    m_AidIsSet = true;
}

bool Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::aidIsSet() const
{
    return m_AidIsSet;
}

void Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::unsetAid()
{
    m_AidIsSet = false;
}
double Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::getType() const
{
    return m_Type;
}

void Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::setType(double value)
{
    m_Type = value;
    m_TypeIsSet = true;
}

bool Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::typeIsSet() const
{
    return m_TypeIsSet;
}

void Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::unsetType()
{
    m_TypeIsSet = false;
}
utility::string_t Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::getDesc() const
{
    return m_Desc;
}


void Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::setDesc(const utility::string_t& value)
{
    m_Desc = value;
    m_DescIsSet = true;
}

bool Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::descIsSet() const
{
    return m_DescIsSet;
}

void Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::unsetDesc()
{
    m_DescIsSet = false;
}
double Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::getWeeklyRecommendNum() const
{
    return m_Weekly_recommend_num;
}

void Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::setWeeklyRecommendNum(double value)
{
    m_Weekly_recommend_num = value;
    m_Weekly_recommend_numIsSet = true;
}

bool Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::weeklyRecommendNumIsSet() const
{
    return m_Weekly_recommend_numIsSet;
}

void Get_social_bilibili_videoinfo_200_response_honor_reply_honor_inner::unsetWeekly_recommend_num()
{
    m_Weekly_recommend_numIsSet = false;
}

}
}
}
}


