/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Get_social_bilibili_videoinfo_200_response_subtitle_list_inner.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::Get_social_bilibili_videoinfo_200_response_subtitle_list_inner()
{
    m_Id = 0.0;
    m_IdIsSet = false;
    m_Lan = utility::conversions::to_string_t("");
    m_LanIsSet = false;
    m_Lan_doc = utility::conversions::to_string_t("");
    m_Lan_docIsSet = false;
    m_Is_lock = false;
    m_Is_lockIsSet = false;
    m_Author_mid = 0.0;
    m_Author_midIsSet = false;
    m_Subtitle_url = utility::conversions::to_string_t("");
    m_Subtitle_urlIsSet = false;
    m_AuthorIsSet = false;
}

Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::~Get_social_bilibili_videoinfo_200_response_subtitle_list_inner()
{
}

void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::validate()
{
    // TODO: implement validation
}

web::json::value Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_LanIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("lan"))] = ModelBase::toJson(m_Lan);
    }
    if(m_Lan_docIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("lan_doc"))] = ModelBase::toJson(m_Lan_doc);
    }
    if(m_Is_lockIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_lock"))] = ModelBase::toJson(m_Is_lock);
    }
    if(m_Author_midIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("author_mid"))] = ModelBase::toJson(m_Author_mid);
    }
    if(m_Subtitle_urlIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("subtitle_url"))] = ModelBase::toJson(m_Subtitle_url);
    }
    if(m_AuthorIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("author"))] = ModelBase::toJson(m_Author);
    }

    return val;
}

bool Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            double refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("lan"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("lan")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLan;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLan);
            setLan(refVal_setLan);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("lan_doc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("lan_doc")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLanDoc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLanDoc);
            setLanDoc(refVal_setLanDoc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_lock"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_lock")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsLock;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsLock);
            setIsLock(refVal_setIsLock);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("author_mid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("author_mid")));
        if(!fieldValue.is_null())
        {
            double refVal_setAuthorMid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAuthorMid);
            setAuthorMid(refVal_setAuthorMid);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subtitle_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subtitle_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSubtitleUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubtitleUrl);
            setSubtitleUrl(refVal_setSubtitleUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("author"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("author")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Get_social_bilibili_videoinfo_200_response_subtitle_list_inner_author> refVal_setAuthor;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAuthor);
            setAuthor(refVal_setAuthor);
            
        }
    }
    return ok;
}

void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_LanIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("lan")), m_Lan));
    }
    if(m_Lan_docIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("lan_doc")), m_Lan_doc));
    }
    if(m_Is_lockIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_lock")), m_Is_lock));
    }
    if(m_Author_midIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("author_mid")), m_Author_mid));
    }
    if(m_Subtitle_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subtitle_url")), m_Subtitle_url));
    }
    if(m_AuthorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("author")), m_Author));
    }
}

bool Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        double refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("lan"))))
    {
        utility::string_t refVal_setLan;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("lan"))), refVal_setLan );
        setLan(refVal_setLan);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("lan_doc"))))
    {
        utility::string_t refVal_setLanDoc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("lan_doc"))), refVal_setLanDoc );
        setLanDoc(refVal_setLanDoc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_lock"))))
    {
        bool refVal_setIsLock;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_lock"))), refVal_setIsLock );
        setIsLock(refVal_setIsLock);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("author_mid"))))
    {
        double refVal_setAuthorMid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("author_mid"))), refVal_setAuthorMid );
        setAuthorMid(refVal_setAuthorMid);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subtitle_url"))))
    {
        utility::string_t refVal_setSubtitleUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subtitle_url"))), refVal_setSubtitleUrl );
        setSubtitleUrl(refVal_setSubtitleUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("author"))))
    {
        std::shared_ptr<Get_social_bilibili_videoinfo_200_response_subtitle_list_inner_author> refVal_setAuthor;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("author"))), refVal_setAuthor );
        setAuthor(refVal_setAuthor);
    }
    return ok;
}


double Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::getId() const
{
    return m_Id;
}

void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::setId(double value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::idIsSet() const
{
    return m_IdIsSet;
}

void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::getLan() const
{
    return m_Lan;
}


void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::setLan(const utility::string_t& value)
{
    m_Lan = value;
    m_LanIsSet = true;
}

bool Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::lanIsSet() const
{
    return m_LanIsSet;
}

void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::unsetLan()
{
    m_LanIsSet = false;
}
utility::string_t Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::getLanDoc() const
{
    return m_Lan_doc;
}


void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::setLanDoc(const utility::string_t& value)
{
    m_Lan_doc = value;
    m_Lan_docIsSet = true;
}

bool Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::lanDocIsSet() const
{
    return m_Lan_docIsSet;
}

void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::unsetLan_doc()
{
    m_Lan_docIsSet = false;
}
bool Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::isIsLock() const
{
    return m_Is_lock;
}

void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::setIsLock(bool value)
{
    m_Is_lock = value;
    m_Is_lockIsSet = true;
}

bool Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::isLockIsSet() const
{
    return m_Is_lockIsSet;
}

void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::unsetIs_lock()
{
    m_Is_lockIsSet = false;
}
double Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::getAuthorMid() const
{
    return m_Author_mid;
}

void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::setAuthorMid(double value)
{
    m_Author_mid = value;
    m_Author_midIsSet = true;
}

bool Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::authorMidIsSet() const
{
    return m_Author_midIsSet;
}

void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::unsetAuthor_mid()
{
    m_Author_midIsSet = false;
}
utility::string_t Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::getSubtitleUrl() const
{
    return m_Subtitle_url;
}


void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::setSubtitleUrl(const utility::string_t& value)
{
    m_Subtitle_url = value;
    m_Subtitle_urlIsSet = true;
}

bool Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::subtitleUrlIsSet() const
{
    return m_Subtitle_urlIsSet;
}

void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::unsetSubtitle_url()
{
    m_Subtitle_urlIsSet = false;
}
std::shared_ptr<Get_social_bilibili_videoinfo_200_response_subtitle_list_inner_author> Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::getAuthor() const
{
    return m_Author;
}


void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::setAuthor(const std::shared_ptr<Get_social_bilibili_videoinfo_200_response_subtitle_list_inner_author>& value)
{
    m_Author = value;
    m_AuthorIsSet = true;
}

bool Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::authorIsSet() const
{
    return m_AuthorIsSet;
}

void Get_social_bilibili_videoinfo_200_response_subtitle_list_inner::unsetAuthor()
{
    m_AuthorIsSet = false;
}

}
}
}
}


