/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner()
{
    m_date = utility::conversions::to_string_t("");
    m_dateIsSet = false;
    m_Contribution_count = 0;
    m_Contribution_countIsSet = false;
    m_Color = utility::conversions::to_string_t("");
    m_ColorIsSet = false;
    m_Weekday = 0;
    m_WeekdayIsSet = false;
}

Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::~Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner()
{
}

void Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::validate()
{
    // TODO: implement validation
}

web::json::value Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_dateIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("date"))] = ModelBase::toJson(m_date);
    }
    if(m_Contribution_countIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("contribution_count"))] = ModelBase::toJson(m_Contribution_count);
    }
    if(m_ColorIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("color"))] = ModelBase::toJson(m_Color);
    }
    if(m_WeekdayIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("weekday"))] = ModelBase::toJson(m_Weekday);
    }

    return val;
}

bool Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("date"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("date")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDate);
            setDate(refVal_setDate);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("contribution_count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("contribution_count")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setContributionCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setContributionCount);
            setContributionCount(refVal_setContributionCount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("color"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("color")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setColor;
            ok &= ModelBase::fromJson(fieldValue, refVal_setColor);
            setColor(refVal_setColor);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("weekday"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("weekday")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setWeekday;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWeekday);
            setWeekday(refVal_setWeekday);
            
        }
    }
    return ok;
}

void Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_dateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("date")), m_date));
    }
    if(m_Contribution_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("contribution_count")), m_Contribution_count));
    }
    if(m_ColorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("color")), m_Color));
    }
    if(m_WeekdayIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("weekday")), m_Weekday));
    }
}

bool Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("date"))))
    {
        utility::string_t refVal_setDate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("date"))), refVal_setDate );
        setDate(refVal_setDate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("contribution_count"))))
    {
        int32_t refVal_setContributionCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("contribution_count"))), refVal_setContributionCount );
        setContributionCount(refVal_setContributionCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("color"))))
    {
        utility::string_t refVal_setColor;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("color"))), refVal_setColor );
        setColor(refVal_setColor);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("weekday"))))
    {
        int32_t refVal_setWeekday;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("weekday"))), refVal_setWeekday );
        setWeekday(refVal_setWeekday);
    }
    return ok;
}


utility::string_t Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::getDate() const
{
    return m_date;
}


void Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::setDate(const utility::string_t& value)
{
    m_date = value;
    m_dateIsSet = true;
}

bool Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::dateIsSet() const
{
    return m_dateIsSet;
}

void Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::unsetdate()
{
    m_dateIsSet = false;
}
int32_t Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::getContributionCount() const
{
    return m_Contribution_count;
}

void Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::setContributionCount(int32_t value)
{
    m_Contribution_count = value;
    m_Contribution_countIsSet = true;
}

bool Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::contributionCountIsSet() const
{
    return m_Contribution_countIsSet;
}

void Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::unsetContribution_count()
{
    m_Contribution_countIsSet = false;
}
utility::string_t Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::getColor() const
{
    return m_Color;
}


void Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::setColor(const utility::string_t& value)
{
    m_Color = value;
    m_ColorIsSet = true;
}

bool Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::colorIsSet() const
{
    return m_ColorIsSet;
}

void Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::unsetColor()
{
    m_ColorIsSet = false;
}
int32_t Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::getWeekday() const
{
    return m_Weekday;
}

void Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::setWeekday(int32_t value)
{
    m_Weekday = value;
    m_WeekdayIsSet = true;
}

bool Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::weekdayIsSet() const
{
    return m_WeekdayIsSet;
}

void Get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner::unsetWeekday()
{
    m_WeekdayIsSet = false;
}

}
}
}
}


