/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Post_translate_stream_request.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Post_translate_stream_request::Post_translate_stream_request()
{
    m_Query = utility::conversions::to_string_t("");
    m_QueryIsSet = false;
    m_To_lang = utility::conversions::to_string_t("");
    m_To_langIsSet = false;
    m_From_lang = utility::conversions::to_string_t("");
    m_From_langIsSet = false;
    m_Tone = utility::conversions::to_string_t("");
    m_ToneIsSet = false;
}

Post_translate_stream_request::~Post_translate_stream_request()
{
}

void Post_translate_stream_request::validate()
{
    // TODO: implement validation
}

web::json::value Post_translate_stream_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_QueryIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("query"))] = ModelBase::toJson(m_Query);
    }
    if(m_To_langIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("to_lang"))] = ModelBase::toJson(m_To_lang);
    }
    if(m_From_langIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("from_lang"))] = ModelBase::toJson(m_From_lang);
    }
    if(m_ToneIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("tone"))] = ModelBase::toJson(m_Tone);
    }

    return val;
}

bool Post_translate_stream_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("query"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("query")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setQuery;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQuery);
            setQuery(refVal_setQuery);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("to_lang"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("to_lang")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setToLang;
            ok &= ModelBase::fromJson(fieldValue, refVal_setToLang);
            setToLang(refVal_setToLang);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("from_lang"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("from_lang")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFromLang;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFromLang);
            setFromLang(refVal_setFromLang);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tone")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTone);
            setTone(refVal_setTone);
            
        }
    }
    return ok;
}

void Post_translate_stream_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_QueryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("query")), m_Query));
    }
    if(m_To_langIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("to_lang")), m_To_lang));
    }
    if(m_From_langIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("from_lang")), m_From_lang));
    }
    if(m_ToneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tone")), m_Tone));
    }
}

bool Post_translate_stream_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("query"))))
    {
        utility::string_t refVal_setQuery;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("query"))), refVal_setQuery );
        setQuery(refVal_setQuery);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("to_lang"))))
    {
        utility::string_t refVal_setToLang;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("to_lang"))), refVal_setToLang );
        setToLang(refVal_setToLang);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("from_lang"))))
    {
        utility::string_t refVal_setFromLang;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("from_lang"))), refVal_setFromLang );
        setFromLang(refVal_setFromLang);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tone"))))
    {
        utility::string_t refVal_setTone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tone"))), refVal_setTone );
        setTone(refVal_setTone);
    }
    return ok;
}


utility::string_t Post_translate_stream_request::getQuery() const
{
    return m_Query;
}


void Post_translate_stream_request::setQuery(const utility::string_t& value)
{
    m_Query = value;
    m_QueryIsSet = true;
}

bool Post_translate_stream_request::queryIsSet() const
{
    return m_QueryIsSet;
}

void Post_translate_stream_request::unsetQuery()
{
    m_QueryIsSet = false;
}
utility::string_t Post_translate_stream_request::getToLang() const
{
    return m_To_lang;
}


void Post_translate_stream_request::setToLang(const utility::string_t& value)
{
    m_To_lang = value;
    m_To_langIsSet = true;
}

bool Post_translate_stream_request::toLangIsSet() const
{
    return m_To_langIsSet;
}

void Post_translate_stream_request::unsetTo_lang()
{
    m_To_langIsSet = false;
}
utility::string_t Post_translate_stream_request::getFromLang() const
{
    return m_From_lang;
}


void Post_translate_stream_request::setFromLang(const utility::string_t& value)
{
    m_From_lang = value;
    m_From_langIsSet = true;
}

bool Post_translate_stream_request::fromLangIsSet() const
{
    return m_From_langIsSet;
}

void Post_translate_stream_request::unsetFrom_lang()
{
    m_From_langIsSet = false;
}
utility::string_t Post_translate_stream_request::getTone() const
{
    return m_Tone;
}


void Post_translate_stream_request::setTone(const utility::string_t& value)
{
    m_Tone = value;
    m_ToneIsSet = true;
}

bool Post_translate_stream_request::toneIsSet() const
{
    return m_ToneIsSet;
}

void Post_translate_stream_request::unsetTone()
{
    m_ToneIsSet = false;
}

}
}
}
}


