/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Post_text_base64_decode_200_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Post_text_base64_decode_200_response::Post_text_base64_decode_200_response()
{
    m_Decoded = utility::conversions::to_string_t("");
    m_DecodedIsSet = false;
}

Post_text_base64_decode_200_response::~Post_text_base64_decode_200_response()
{
}

void Post_text_base64_decode_200_response::validate()
{
    // TODO: implement validation
}

web::json::value Post_text_base64_decode_200_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_DecodedIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("decoded"))] = ModelBase::toJson(m_Decoded);
    }

    return val;
}

bool Post_text_base64_decode_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("decoded"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("decoded")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDecoded;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDecoded);
            setDecoded(refVal_setDecoded);
            
        }
    }
    return ok;
}

void Post_text_base64_decode_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_DecodedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("decoded")), m_Decoded));
    }
}

bool Post_text_base64_decode_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("decoded"))))
    {
        utility::string_t refVal_setDecoded;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("decoded"))), refVal_setDecoded );
        setDecoded(refVal_setDecoded);
    }
    return ok;
}


utility::string_t Post_text_base64_decode_200_response::getDecoded() const
{
    return m_Decoded;
}


void Post_text_base64_decode_200_response::setDecoded(const utility::string_t& value)
{
    m_Decoded = value;
    m_DecodedIsSet = true;
}

bool Post_text_base64_decode_200_response::decodedIsSet() const
{
    return m_DecodedIsSet;
}

void Post_text_base64_decode_200_response::unsetDecoded()
{
    m_DecodedIsSet = false;
}

}
}
}
}


