/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Post_convert_json_200_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Post_convert_json_200_response::Post_convert_json_200_response()
{
    m_Content = utility::conversions::to_string_t("");
    m_ContentIsSet = false;
}

Post_convert_json_200_response::~Post_convert_json_200_response()
{
}

void Post_convert_json_200_response::validate()
{
    // TODO: implement validation
}

web::json::value Post_convert_json_200_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ContentIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("content"))] = ModelBase::toJson(m_Content);
    }

    return val;
}

bool Post_convert_json_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("content"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("content")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setContent;
            ok &= ModelBase::fromJson(fieldValue, refVal_setContent);
            setContent(refVal_setContent);
            
        }
    }
    return ok;
}

void Post_convert_json_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ContentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("content")), m_Content));
    }
}

bool Post_convert_json_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("content"))))
    {
        utility::string_t refVal_setContent;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("content"))), refVal_setContent );
        setContent(refVal_setContent);
    }
    return ok;
}


utility::string_t Post_convert_json_200_response::getContent() const
{
    return m_Content;
}


void Post_convert_json_200_response::setContent(const utility::string_t& value)
{
    m_Content = value;
    m_ContentIsSet = true;
}

bool Post_convert_json_200_response::contentIsSet() const
{
    return m_ContentIsSet;
}

void Post_convert_json_200_response::unsetContent()
{
    m_ContentIsSet = false;
}

}
}
}
}


