/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Post_text_convert_400_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Post_text_convert_400_response::Post_text_convert_400_response()
{
    m_Error_code = utility::conversions::to_string_t("");
    m_Error_codeIsSet = false;
    m_Error_message = utility::conversions::to_string_t("");
    m_Error_messageIsSet = false;
    m_Error_details = utility::conversions::to_string_t("");
    m_Error_detailsIsSet = false;
}

Post_text_convert_400_response::~Post_text_convert_400_response()
{
}

void Post_text_convert_400_response::validate()
{
    // TODO: implement validation
}

web::json::value Post_text_convert_400_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Error_codeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("error_code"))] = ModelBase::toJson(m_Error_code);
    }
    if(m_Error_messageIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("error_message"))] = ModelBase::toJson(m_Error_message);
    }
    if(m_Error_detailsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("error_details"))] = ModelBase::toJson(m_Error_details);
    }

    return val;
}

bool Post_text_convert_400_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("error_code"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("error_code")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setErrorCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setErrorCode);
            setErrorCode(refVal_setErrorCode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("error_message"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("error_message")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setErrorMessage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setErrorMessage);
            setErrorMessage(refVal_setErrorMessage);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("error_details"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("error_details")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setErrorDetails;
            ok &= ModelBase::fromJson(fieldValue, refVal_setErrorDetails);
            setErrorDetails(refVal_setErrorDetails);
            
        }
    }
    return ok;
}

void Post_text_convert_400_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Error_codeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("error_code")), m_Error_code));
    }
    if(m_Error_messageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("error_message")), m_Error_message));
    }
    if(m_Error_detailsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("error_details")), m_Error_details));
    }
}

bool Post_text_convert_400_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("error_code"))))
    {
        utility::string_t refVal_setErrorCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("error_code"))), refVal_setErrorCode );
        setErrorCode(refVal_setErrorCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("error_message"))))
    {
        utility::string_t refVal_setErrorMessage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("error_message"))), refVal_setErrorMessage );
        setErrorMessage(refVal_setErrorMessage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("error_details"))))
    {
        utility::string_t refVal_setErrorDetails;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("error_details"))), refVal_setErrorDetails );
        setErrorDetails(refVal_setErrorDetails);
    }
    return ok;
}


utility::string_t Post_text_convert_400_response::getErrorCode() const
{
    return m_Error_code;
}


void Post_text_convert_400_response::setErrorCode(const utility::string_t& value)
{
    m_Error_code = value;
    m_Error_codeIsSet = true;
}

bool Post_text_convert_400_response::errorCodeIsSet() const
{
    return m_Error_codeIsSet;
}

void Post_text_convert_400_response::unsetError_code()
{
    m_Error_codeIsSet = false;
}
utility::string_t Post_text_convert_400_response::getErrorMessage() const
{
    return m_Error_message;
}


void Post_text_convert_400_response::setErrorMessage(const utility::string_t& value)
{
    m_Error_message = value;
    m_Error_messageIsSet = true;
}

bool Post_text_convert_400_response::errorMessageIsSet() const
{
    return m_Error_messageIsSet;
}

void Post_text_convert_400_response::unsetError_message()
{
    m_Error_messageIsSet = false;
}
utility::string_t Post_text_convert_400_response::getErrorDetails() const
{
    return m_Error_details;
}


void Post_text_convert_400_response::setErrorDetails(const utility::string_t& value)
{
    m_Error_details = value;
    m_Error_detailsIsSet = true;
}

bool Post_text_convert_400_response::errorDetailsIsSet() const
{
    return m_Error_detailsIsSet;
}

void Post_text_convert_400_response::unsetError_details()
{
    m_Error_detailsIsSet = false;
}

}
}
}
}


