/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Post_translate_stream_400_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Post_translate_stream_400_response::Post_translate_stream_400_response()
{
    m_Error = utility::conversions::to_string_t("");
    m_ErrorIsSet = false;
    m_CodeIsSet = false;
}

Post_translate_stream_400_response::~Post_translate_stream_400_response()
{
}

void Post_translate_stream_400_response::validate()
{
    // TODO: implement validation
}

web::json::value Post_translate_stream_400_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ErrorIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("error"))] = ModelBase::toJson(m_Error);
    }
    if(m_CodeIsSet)
    {   
        
        utility::string_t refVal = fromCodeEnum(m_Code);
        val[utility::conversions::to_string_t(_XPLATSTR("code"))] = ModelBase::toJson(refVal);
        
    }

    return val;
}

bool Post_translate_stream_400_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("error"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("error")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setError;
            ok &= ModelBase::fromJson(fieldValue, refVal_setError);
            setError(refVal_setError);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("code")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCode);
            
            setCode(toCodeEnum(refVal_setCode));
            
        }
    }
    return ok;
}

void Post_translate_stream_400_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ErrorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("error")), m_Error));
    }
    if(m_CodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("code")), fromCodeEnum(m_Code)));
    }
}

bool Post_translate_stream_400_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("error"))))
    {
        utility::string_t refVal_setError;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("error"))), refVal_setError );
        setError(refVal_setError);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        utility::string_t refVal_setCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("code"))), refVal_setCode );
        setCode(toCodeEnum(refVal_setCode));
    }
    return ok;
}

Post_translate_stream_400_response::CodeEnum Post_translate_stream_400_response::toCodeEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("INVALID_REQUEST")) {
        return CodeEnum::INVALID_REQUEST;
    }
    
    if (value == utility::conversions::to_string_t("MISSING_QUERY")) {
        return CodeEnum::MISSING_QUERY;
    }
    
    if (value == utility::conversions::to_string_t("MISSING_TARGET_LANG")) {
        return CodeEnum::MISSING_TARGET_LANG;
    }
    
    throw std::invalid_argument("Invalid value for conversion to CodeEnum");
}


const utility::string_t Post_translate_stream_400_response::fromCodeEnum(const CodeEnum value) const
{
    switch(value)
    {
        
        case CodeEnum::INVALID_REQUEST: return utility::conversions::to_string_t("INVALID_REQUEST");
        
        case CodeEnum::MISSING_QUERY: return utility::conversions::to_string_t("MISSING_QUERY");
        
        case CodeEnum::MISSING_TARGET_LANG: return utility::conversions::to_string_t("MISSING_TARGET_LANG");
        
    }
}


utility::string_t Post_translate_stream_400_response::getError() const
{
    return m_Error;
}


void Post_translate_stream_400_response::setError(const utility::string_t& value)
{
    m_Error = value;
    m_ErrorIsSet = true;
}

bool Post_translate_stream_400_response::errorIsSet() const
{
    return m_ErrorIsSet;
}

void Post_translate_stream_400_response::unsetError()
{
    m_ErrorIsSet = false;
}
Post_translate_stream_400_response::CodeEnum Post_translate_stream_400_response::getCode() const
{
    return m_Code;
}


void Post_translate_stream_400_response::setCode(const CodeEnum value)
{
    m_Code = value;
    m_CodeIsSet = true;
}

bool Post_translate_stream_400_response::codeIsSet() const
{
    return m_CodeIsSet;
}

void Post_translate_stream_400_response::unsetCode()
{
    m_CodeIsSet = false;
}

}
}
}
}


