/**
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Post_search_aggregate_200_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Post_search_aggregate_200_response::Post_search_aggregate_200_response()
{
    m_Query = utility::conversions::to_string_t("");
    m_QueryIsSet = false;
    m_Total_results = 0;
    m_Total_resultsIsSet = false;
    m_ResultsIsSet = false;
    m_SourcesIsSet = false;
    m_Process_time_ms = 0;
    m_Process_time_msIsSet = false;
    m_Cached = false;
    m_CachedIsSet = false;
}

Post_search_aggregate_200_response::~Post_search_aggregate_200_response()
{
}

void Post_search_aggregate_200_response::validate()
{
    // TODO: implement validation
}

web::json::value Post_search_aggregate_200_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_QueryIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("query"))] = ModelBase::toJson(m_Query);
    }
    if(m_Total_resultsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("total_results"))] = ModelBase::toJson(m_Total_results);
    }
    if(m_ResultsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("results"))] = ModelBase::toJson(m_Results);
    }
    if(m_SourcesIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("sources"))] = ModelBase::toJson(m_Sources);
    }
    if(m_Process_time_msIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("process_time_ms"))] = ModelBase::toJson(m_Process_time_ms);
    }
    if(m_CachedIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("cached"))] = ModelBase::toJson(m_Cached);
    }

    return val;
}

bool Post_search_aggregate_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("query"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("query")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setQuery;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQuery);
            setQuery(refVal_setQuery);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("total_results"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("total_results")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotalResults;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalResults);
            setTotalResults(refVal_setTotalResults);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("results"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("results")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Post_search_aggregate_200_response_results_inner>> refVal_setResults;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResults);
            setResults(refVal_setResults);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("sources"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("sources")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Post_search_aggregate_200_response_sources_inner>> refVal_setSources;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSources);
            setSources(refVal_setSources);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("process_time_ms"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("process_time_ms")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setProcessTimeMs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProcessTimeMs);
            setProcessTimeMs(refVal_setProcessTimeMs);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("cached"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("cached")));
        if(!fieldValue.is_null())
        {
            bool refVal_setCached;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCached);
            setCached(refVal_setCached);
            
        }
    }
    return ok;
}

void Post_search_aggregate_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_QueryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("query")), m_Query));
    }
    if(m_Total_resultsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("total_results")), m_Total_results));
    }
    if(m_ResultsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("results")), m_Results));
    }
    if(m_SourcesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("sources")), m_Sources));
    }
    if(m_Process_time_msIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("process_time_ms")), m_Process_time_ms));
    }
    if(m_CachedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("cached")), m_Cached));
    }
}

bool Post_search_aggregate_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("query"))))
    {
        utility::string_t refVal_setQuery;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("query"))), refVal_setQuery );
        setQuery(refVal_setQuery);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("total_results"))))
    {
        int32_t refVal_setTotalResults;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("total_results"))), refVal_setTotalResults );
        setTotalResults(refVal_setTotalResults);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("results"))))
    {
        std::vector<std::shared_ptr<Post_search_aggregate_200_response_results_inner>> refVal_setResults;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("results"))), refVal_setResults );
        setResults(refVal_setResults);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("sources"))))
    {
        std::vector<std::shared_ptr<Post_search_aggregate_200_response_sources_inner>> refVal_setSources;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("sources"))), refVal_setSources );
        setSources(refVal_setSources);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("process_time_ms"))))
    {
        int32_t refVal_setProcessTimeMs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("process_time_ms"))), refVal_setProcessTimeMs );
        setProcessTimeMs(refVal_setProcessTimeMs);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("cached"))))
    {
        bool refVal_setCached;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("cached"))), refVal_setCached );
        setCached(refVal_setCached);
    }
    return ok;
}


utility::string_t Post_search_aggregate_200_response::getQuery() const
{
    return m_Query;
}


void Post_search_aggregate_200_response::setQuery(const utility::string_t& value)
{
    m_Query = value;
    m_QueryIsSet = true;
}

bool Post_search_aggregate_200_response::queryIsSet() const
{
    return m_QueryIsSet;
}

void Post_search_aggregate_200_response::unsetQuery()
{
    m_QueryIsSet = false;
}
int32_t Post_search_aggregate_200_response::getTotalResults() const
{
    return m_Total_results;
}

void Post_search_aggregate_200_response::setTotalResults(int32_t value)
{
    m_Total_results = value;
    m_Total_resultsIsSet = true;
}

bool Post_search_aggregate_200_response::totalResultsIsSet() const
{
    return m_Total_resultsIsSet;
}

void Post_search_aggregate_200_response::unsetTotal_results()
{
    m_Total_resultsIsSet = false;
}
std::vector<std::shared_ptr<Post_search_aggregate_200_response_results_inner>> Post_search_aggregate_200_response::getResults() const
{
    return m_Results;
}


void Post_search_aggregate_200_response::setResults(const std::vector<std::shared_ptr<Post_search_aggregate_200_response_results_inner>>& value)
{
    m_Results = value;
    m_ResultsIsSet = true;
}

bool Post_search_aggregate_200_response::resultsIsSet() const
{
    return m_ResultsIsSet;
}

void Post_search_aggregate_200_response::unsetResults()
{
    m_ResultsIsSet = false;
}
std::vector<std::shared_ptr<Post_search_aggregate_200_response_sources_inner>> Post_search_aggregate_200_response::getSources() const
{
    return m_Sources;
}


void Post_search_aggregate_200_response::setSources(const std::vector<std::shared_ptr<Post_search_aggregate_200_response_sources_inner>>& value)
{
    m_Sources = value;
    m_SourcesIsSet = true;
}

bool Post_search_aggregate_200_response::sourcesIsSet() const
{
    return m_SourcesIsSet;
}

void Post_search_aggregate_200_response::unsetSources()
{
    m_SourcesIsSet = false;
}
int32_t Post_search_aggregate_200_response::getProcessTimeMs() const
{
    return m_Process_time_ms;
}

void Post_search_aggregate_200_response::setProcessTimeMs(int32_t value)
{
    m_Process_time_ms = value;
    m_Process_time_msIsSet = true;
}

bool Post_search_aggregate_200_response::processTimeMsIsSet() const
{
    return m_Process_time_msIsSet;
}

void Post_search_aggregate_200_response::unsetProcess_time_ms()
{
    m_Process_time_msIsSet = false;
}
bool Post_search_aggregate_200_response::isCached() const
{
    return m_Cached;
}

void Post_search_aggregate_200_response::setCached(bool value)
{
    m_Cached = value;
    m_CachedIsSet = true;
}

bool Post_search_aggregate_200_response::cachedIsSet() const
{
    return m_CachedIsSet;
}

void Post_search_aggregate_200_response::unsetCached()
{
    m_CachedIsSet = false;
}

}
}
}
}


