/**
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DefaultApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_DefaultApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_DefaultApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/Get_search_engines_200_response.h"
#include "CppRestOpenAPIClient/model/Get_sensitive_word_analyze_query_400_response.h"
#include "CppRestOpenAPIClient/model/Post_search_aggregate_200_response.h"
#include "CppRestOpenAPIClient/model/Post_search_aggregate_400_response.h"
#include "CppRestOpenAPIClient/model/Post_search_aggregate_401_response.h"
#include "CppRestOpenAPIClient/model/Post_search_aggregate_429_response.h"
#include "CppRestOpenAPIClient/model/Post_search_aggregate_500_response.h"
#include "CppRestOpenAPIClient/model/Post_search_aggregate_request.h"
#include "CppRestOpenAPIClient/model/Post_sensitive_word_analyze_200_response.h"
#include "CppRestOpenAPIClient/model/Post_sensitive_word_analyze_400_response.h"
#include "CppRestOpenAPIClient/model/Post_sensitive_word_analyze_401_response.h"
#include "CppRestOpenAPIClient/model/Post_sensitive_word_analyze_429_response.h"
#include "CppRestOpenAPIClient/model/Post_sensitive_word_analyze_request.h"
#include "CppRestOpenAPIClient/model/Post_sensitive_word_quick_check_200_response.h"
#include "CppRestOpenAPIClient/model/Post_sensitive_word_quick_check_request.h"
#include "CppRestOpenAPIClient/model/Post_text_analyze_400_response.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  DefaultApi 
{
public:

    explicit DefaultApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~DefaultApi();

    /// <summary>
    /// 搜索引擎配置
    /// </summary>
    /// <remarks>
    /// 获取搜索功能的详细信息，包括支持的能力、参数限制和使用说明。  ## 功能概述  此接口返回搜索功能的完整配置信息，你可以用它来： - 了解当前可用的搜索能力（如站内搜索、文件类型过滤等） - 获取参数的默认值和限制范围 - 查看当前配置版本和可用状态  适合在应用初始化时调用，或用于动态配置搜索界面。       
    /// </remarks>
    pplx::task<std::shared_ptr<Get_search_engines_200_response>> getSearchEngines(
    ) const;
    /// <summary>
    /// 敏感词分析 (GET)
    /// </summary>
    /// <remarks>
    /// 通过URL查询参数分析单个关键词，便于GET请求调用。
    /// </remarks>
    /// <param name="keyword">要分析的关键词，最长1,000字符。</param>
    pplx::task<std::shared_ptr<Post_sensitive_word_analyze_200_response>> getSensitiveWordAnalyzeQuery(
        utility::string_t keyword
    ) const;
    /// <summary>
    /// 智能搜索
    /// </summary>
    /// <remarks>
    /// 想在你的应用中集成搜索功能？这个接口可以帮你轻松实现实时网页搜索。  ## 功能概述  UAPI Pro Search 可以根据查询内容返回更相关的搜索结果。你可以用它搜索任何关键词，也可以限定在特定网站或特定文件类型中搜索。  - **实时网页搜索**: 毫秒级响应，快速返回搜索结果 - **智能排序**: 根据查询内容返回更相关的结果 - **时间排序**: 支持按发布时间排序，获取最新内容 - **时间范围过滤**: 支持按天/周/月/年过滤结果 - **站内搜索**: 支持 &#x60;site:&#x60; 操作符，在指定网站内搜索 - **文件类型过滤**: 支持 &#x60;filetype:&#x60; 操作符，快速找到 PDF、Word 等特定格式文件       
    /// </remarks>
    /// <param name="postSearchAggregateRequest"></param>
    pplx::task<std::shared_ptr<Post_search_aggregate_200_response>> postSearchAggregate(
        std::shared_ptr<Post_search_aggregate_request> postSearchAggregateRequest
    ) const;
    /// <summary>
    /// 分析敏感词
    /// </summary>
    /// <remarks>
    /// 分析单个或多个关键词的敏感程度，返回标准化风险标签与置信度结果。  ## 功能概述  - **风险分析**: 结合文本内容给出语义层面的风险判断。 - **响应稳定**: 兼顾高频调用场景下的处理效率和响应速度。 - **并发支持**: 支持批量并发处理，单次最多可分析100个关键词。 - **输入限制**: 单条关键词最多 1,000 字符，总字符数最多 20,000。 - **标准标签**: 返回 &#x60;label&#x60; 字段，明确区分 &#x60;sensitive&#x60; 与 &#x60;normal&#x60;。 - **分类清晰**: 返回 &#x60;category&#x60; 字段，用于标识具体风险类别。 - **置信度输出**: 返回 &#x60;confidence&#x60; 字段，范围为0.0到1.0。  ## 响应字段说明  | 字段 | 类型 | 说明 | |------|------|------| | &#x60;results&#x60; | array | 分析结果对象的数组。 | | &#x60;results[].k&#x60; | string | 您在请求中提供的原始关键词。 | | &#x60;results[].label&#x60; | string | 核心判断字段：&#x60;sensitive&#x60;(敏感)、&#x60;normal&#x60;(正常)。 | | &#x60;results[].category&#x60; | string | 风险分类：&#x60;safe&#x60;(安全)、&#x60;threat&#x60;(威胁)、&#x60;porn&#x60;(色情)、&#x60;fraud&#x60;(欺诈)、&#x60;insult&#x60;(辱骂)。 | | &#x60;results[].confidence&#x60; | number | 当前分类的置信度，范围0.0到1.0。 | | &#x60;total&#x60; | integer | 本次请求成功分析的关键词总数。 |       
    /// </remarks>
    /// <param name="postSensitiveWordAnalyzeRequest">包含待检测关键词列表 &#x60;keywords&#x60; 的 JSON 对象。单条关键词最多 1,000 字符，总字符数最多 20,000。</param>
    pplx::task<std::shared_ptr<Post_sensitive_word_analyze_200_response>> postSensitiveWordAnalyze(
        std::shared_ptr<Post_sensitive_word_analyze_request> postSensitiveWordAnalyzeRequest
    ) const;
    /// <summary>
    /// 敏感词检测（快速）
    /// </summary>
    /// <remarks>
    /// 在你的社区或应用中，需要过滤不适合展示的内容时，这个接口可以帮你快速完成检测。  ## 功能概述  这个接口可以识别文本中的敏感词，并返回是否命中、命中词列表等结果，适合用于评论区、社区、论坛和内容发布场景。  ### 主要特性  - **快速检测**：能够一次处理整段文本中的多个命中内容 - **简繁体支持**：支持简体中文、繁体中文和混合文本检测 - **结果直观**：返回清晰的检测结果，方便直接接入审核流程 - **响应稳定**：适合日常内容审核和批量检查场景  无论是论坛、社交平台还是评论系统，这个接口都能帮你快速构建内容审核功能。
    /// </remarks>
    /// <param name="postSensitiveWordQuickCheckRequest">包含待检测文本 &#39;text&#39; 的JSON对象</param>
    pplx::task<std::shared_ptr<Post_sensitive_word_quick_check_200_response>> postSensitiveWordQuickCheck(
        std::shared_ptr<Post_sensitive_word_quick_check_request> postSensitiveWordQuickCheckRequest
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_DefaultApi_H_ */

